services:
  mongoviewer:
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_SERVER: cordaria-db-aqhha5
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_BASICAUTH_USERNAME: ''
      ME_CONFIG_BASICAUTH_PASSWORD: ''
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: ee1sy3xdctioafcc
      ME_CONFIG_MONGODB_URL: mongodb://mongo:ee1sy3xdctioafcc@cordaria-db-aqhha5:27017
    ports:
      - '8081:8081'