version: "3"

services:
  my-app-dev:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
      - "24678:24678"
      - "9229:9229"
    volumes:
      - .:/src
