version: "3"

services:
  app-dev:
    container_name: app-dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - $APP_DEVELOP_PORT:$APP_DEVELOP_PORT
      - "24678:24678"
      - "9229:9229"
    volumes:
      - .:/src
