# syntax = docker/dockerfile:1

ARG NODE_VERSION=20.10.0

FROM node:${NODE_VERSION}-slim as base

ARG PORT=8000

ENV NODE_ENV=development

WORKDIR /src

# Build
FROM base as build

COPY --link package.json package-lock.json ./

RUN npm install --production=false

COPY --link . .

# Run
FROM base

ENV PORT=$PORT

EXPOSE 9229

CMD [ "npm", "run", "dev" ]