export const useLessons = () => {
  /**
   * Represents a collection of lessons for different string instruments.
   * Each lesson contains various attributes such as id, level, firstFinger, stringNumber, bpm, and message.
   *
   * @property {Object} lessons - The main object containing all lessons.
   * @property {Array<Object>} lessons.fourStrings - Lessons for four-string instruments.
   * @property {Array<Object>} lessons.sixStrings - Lessons for six-string instruments.
   *
   * @typedef {Object} Lesson
   * @property {number} id - The unique identifier for the lesson.
   * @property {string} level - The difficulty level of the lesson (e.g., 'Tutorial', 'Iniciante', 'Básico I', etc.).
   * @property {number} firstFinger - The finger number to be used first in the lesson.
   * @property {string} stringNumber - The string number to be played in the lesson.
   * @property {number} bpm - The beats per minute for the lesson.
   * @property {string} message - A message associated with the lesson, often providing feedback or achievements.
   */
  const lessons = {
    fourStrings: [
      {
        id: 1,
        level: "Tutorial",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 30,
        message: "",
      },
      {
        id: 2,
        level: "Tutorial",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 30,
        message: "",
      },
      {
        id: 3,
        level: "Tutorial",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 32,
        message: "",
      },
      {
        id: 4,
        level: "Tutorial",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 32,
        message: "",
      },
      {
        id: 5,
        level: "Tutorial",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 34,
        message: "",
      },
      {
        id: 6,
        level: "Tutorial",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 34,
        message: "",
      },
      {
        id: 7,
        level: "Tutorial",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 36,
        message: "",
      },
      {
        id: 8,
        level: "Tutorial",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 36,
        message: "",
      },
      {
        id: 9,
        level: "Tutorial",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 38,
        message: "",
      },
      {
        id: 10,
        level: "Tutorial",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 38,
        message: "Você concluiu o tutorial! Ganhou o 1º troféu!",
      },
      {
        id: 11,
        level: "Iniciante",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 40,
        message: "",
      },
      {
        id: 12,
        level: "Iniciante",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 40,
        message: "",
      },
      {
        id: 13,
        level: "Iniciante",
        firstFinger: 1,
        stringNumber: "1",
        bpm: 42,
        message: "",
      },
      {
        id: 14,
        level: "Iniciante",
        firstFinger: 1,
        stringNumber: "1",
        bpm: 42,
        message: "",
      },
      {
        id: 15,
        level: "Iniciante",
        firstFinger: 2,
        stringNumber: "1",
        bpm: 44,
        message: "",
      },
      {
        id: 16,
        level: "Iniciante",
        firstFinger: 2,
        stringNumber: "1",
        bpm: 44,
        message: "",
      },
      {
        id: 17,
        level: "Iniciante",
        firstFinger: 3,
        stringNumber: "1",
        bpm: 46,
        message: "",
      },
      {
        id: 18,
        level: "Iniciante",
        firstFinger: 3,
        stringNumber: "1",
        bpm: 48,
        message: "",
      },
      {
        id: 19,
        level: "Iniciante",
        firstFinger: 4,
        stringNumber: "1",
        bpm: 48,
        message: "",
      },
      {
        id: 20,
        level: "Iniciante",
        firstFinger: 4,
        stringNumber: "1",
        bpm: 48,
        message:
          "Você exercitou todos os dedos. Agora vamos tentar o mesmo com outras cordas! Ganhou o 2º troféu!",
      },
      {
        id: 21,
        level: "Básico I",
        firstFinger: 0,
        stringNumber: "2",
        bpm: 40,
        message: "",
      },
      {
        id: 22,
        level: "Básico I",
        firstFinger: 0,
        stringNumber: "2",
        bpm: 42,
        message: "",
      },
      {
        id: 23,
        level: "Básico I",
        firstFinger: 1,
        stringNumber: "2",
        bpm: 40,
        message: "",
      },
      {
        id: 24,
        level: "Básico I",
        firstFinger: 1,
        stringNumber: "2",
        bpm: 42,
        message: "",
      },
      {
        id: 25,
        level: "Básico I",
        firstFinger: 2,
        stringNumber: "2",
        bpm: 42,
        message: "",
      },
      {
        id: 26,
        level: "Básico I",
        firstFinger: 2,
        stringNumber: "2",
        bpm: 44,
        message: "",
      },
      {
        id: 27,
        level: "Básico I",
        firstFinger: 3,
        stringNumber: "2",
        bpm: 44,
        message: "",
      },
      {
        id: 28,
        level: "Básico I",
        firstFinger: 3,
        stringNumber: "2",
        bpm: 46,
        message: "",
      },
      {
        id: 29,
        level: "Básico I",
        firstFinger: 4,
        stringNumber: "2",
        bpm: 46,
        message: "",
      },
      {
        id: 30,
        level: "Básico I",
        firstFinger: 4,
        stringNumber: "2",
        bpm: 48,
        message: "Você exercitou a segunda corda!",
      },
      {
        id: 31,
        level: "Básico I",
        firstFinger: 0,
        stringNumber: "3",
        bpm: 40,
        message: "",
      },
      {
        id: 32,
        level: "Básico I",
        firstFinger: 0,
        stringNumber: "3",
        bpm: 42,
        message: "",
      },
      {
        id: 33,
        level: "Básico I",
        firstFinger: 1,
        stringNumber: "3",
        bpm: 40,
        message: "",
      },
      {
        id: 34,
        level: "Básico I",
        firstFinger: 1,
        stringNumber: "3",
        bpm: 42,
        message: "",
      },
      {
        id: 35,
        level: "Básico I",
        firstFinger: 2,
        stringNumber: "3",
        bpm: 42,
        message: "",
      },
      {
        id: 36,
        level: "Básico I",
        firstFinger: 2,
        stringNumber: "3",
        bpm: 44,
        message: "",
      },
      {
        id: 37,
        level: "Básico I",
        firstFinger: 3,
        stringNumber: "3",
        bpm: 44,
        message: "",
      },
      {
        id: 38,
        level: "Básico I",
        firstFinger: 3,
        stringNumber: "3",
        bpm: 46,
        message: "",
      },
      {
        id: 39,
        level: "Básico I",
        firstFinger: 4,
        stringNumber: "3",
        bpm: 46,
        message: "",
      },
      {
        id: 40,
        level: "Básico I",
        firstFinger: 4,
        stringNumber: "3",
        bpm: 48,
        message: "Você exercitou a terceira corda! Ganhou o terceiro troféu!",
      },
      {
        id: 41,
        level: "Básico II",
        firstFinger: 1,
        stringNumber: "4",
        bpm: 40,
        message: "",
      },
      {
        id: 42,
        level: "Básico II",
        firstFinger: 1,
        stringNumber: "4",
        bpm: 42,
        message: "",
      },
      {
        id: 43,
        level: "Básico II",
        firstFinger: 2,
        stringNumber: "4",
        bpm: 42,
        message: "",
      },
      {
        id: 44,
        level: "Básico II",
        firstFinger: 2,
        stringNumber: "4",
        bpm: 44,
        message: "",
      },
      {
        id: 45,
        level: "Básico II",
        firstFinger: 3,
        stringNumber: "4",
        bpm: 44,
        message: "",
      },
      {
        id: 46,
        level: "Básico II",
        firstFinger: 3,
        stringNumber: "4",
        bpm: 46,
        message: "",
      },
      {
        id: 47,
        level: "Básico II",
        firstFinger: 4,
        stringNumber: "4",
        bpm: 46,
        message: "",
      },
      {
        id: 48,
        level: "Básico II",
        firstFinger: 4,
        stringNumber: "4",
        bpm: 48,
        message: "",
      },
      {
        id: 49,
        level: "Básico II",
        firstFinger: 1,
        stringNumber: "4",
        bpm: 40,
        message: "",
      },
      {
        id: 50,
        level: "Básico II",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 42,
        message: "Você exercitou todas as cordas!",
      },
      {
        id: 51,
        level: "Básico II",
        firstFinger: 1,
        stringNumber: "1",
        bpm: 42,
        message: "",
      },
      {
        id: 52,
        level: "Básico II",
        firstFinger: 2,
        stringNumber: "1",
        bpm: 42,
        message: "",
      },
      {
        id: 53,
        level: "Básico II",
        firstFinger: 3,
        stringNumber: "1",
        bpm: 42,
        message: "",
      },
      {
        id: 54,
        level: "Básico II",
        firstFinger: 4,
        stringNumber: "1",
        bpm: 42,
        message: "",
      },
      {
        id: 55,
        level: "Básico II",
        firstFinger: 0,
        stringNumber: "2",
        bpm: 44,
        message: "",
      },
      {
        id: 56,
        level: "Básico II",
        firstFinger: 1,
        stringNumber: "2",
        bpm: 44,
        message: "",
      },
      {
        id: 57,
        level: "Básico II",
        firstFinger: 2,
        stringNumber: "2",
        bpm: 44,
        message: "",
      },
      {
        id: 58,
        level: "Básico II",
        firstFinger: 3,
        stringNumber: "2",
        bpm: 44,
        message: "",
      },
      {
        id: 59,
        level: "Básico II",
        firstFinger: 4,
        stringNumber: "2",
        bpm: 44,
        message: "",
      },
      {
        id: 60,
        level: "Básico II",
        firstFinger: 0,
        stringNumber: "3",
        bpm: 46,
        message: "",
      },
      {
        id: 61,
        level: "Básico II",
        firstFinger: 1,
        stringNumber: "3",
        bpm: 46,
        message: "",
      },
      {
        id: 62,
        level: "Básico II",
        firstFinger: 2,
        stringNumber: "3",
        bpm: 46,
        message: "",
      },
      {
        id: 63,
        level: "Básico II",
        firstFinger: 3,
        stringNumber: "3",
        bpm: 46,
        message: "",
      },
      {
        id: 64,
        level: "Básico II",
        firstFinger: 4,
        stringNumber: "3",
        bpm: 46,
        message: "",
      },
      {
        id: 65,
        level: "Básico II",
        firstFinger: 0,
        stringNumber: "4",
        bpm: 48,
        message: "",
      },
      {
        id: 66,
        level: "Básico II",
        firstFinger: 1,
        stringNumber: "4",
        bpm: 48,
        message: "",
      },
      {
        id: 67,
        level: "Básico II",
        firstFinger: 2,
        stringNumber: "4",
        bpm: 48,
        message: "",
      },
      {
        id: 68,
        level: "Básico II",
        firstFinger: 3,
        stringNumber: "4",
        bpm: 48,
        message: "",
      },
      {
        id: 69,
        level: "Básico II",
        firstFinger: 4,
        stringNumber: "4",
        bpm: 48,
        message: "",
      },
      {
        id: 70,
        level: "Básico II",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 50,
        message: "Que tal dar uma acelerada? Ganhou o quarto troféu!",
      },
      {
        id: 71,
        level: "Intermediário I",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 50,
        message: "",
      },
      {
        id: 72,
        level: "Intermediário I",
        firstFinger: 1,
        stringNumber: "1",
        bpm: 52,
        message: "",
      },
      {
        id: 73,
        level: "Intermediário I",
        firstFinger: 2,
        stringNumber: "1",
        bpm: 54,
        message: "",
      },
      {
        id: 74,
        level: "Intermediário I",
        firstFinger: 3,
        stringNumber: "1",
        bpm: 56,
        message: "",
      },
      {
        id: 75,
        level: "Intermediário I",
        firstFinger: 4,
        stringNumber: "1",
        bpm: 58,
        message: "",
      },
      {
        id: 76,
        level: "Intermediário I",
        firstFinger: 0,
        stringNumber: "2",
        bpm: 58,
        message: "",
      },
      {
        id: 77,
        level: "Intermediário I",
        firstFinger: 1,
        stringNumber: "2",
        bpm: 60,
        message: "",
      },
      {
        id: 78,
        level: "Intermediário I",
        firstFinger: 2,
        stringNumber: "2",
        bpm: 62,
        message: "",
      },
      {
        id: 79,
        level: "Intermediário I",
        firstFinger: 3,
        stringNumber: "2",
        bpm: 64,
        message: "",
      },
      {
        id: 80,
        level: "Intermediário I",
        firstFinger: 4,
        stringNumber: "2",
        bpm: 66,
        message: "",
      },
      {
        id: 81,
        level: "Intermediário I",
        firstFinger: 0,
        stringNumber: "3",
        bpm: 66,
        message: "",
      },
      {
        id: 82,
        level: "Intermediário I",
        firstFinger: 1,
        stringNumber: "3",
        bpm: 68,
        message: "",
      },
      {
        id: 83,
        level: "Intermediário I",
        firstFinger: 2,
        stringNumber: "3",
        bpm: 70,
        message: "",
      },
      {
        id: 84,
        level: "Intermediário I",
        firstFinger: 3,
        stringNumber: "3",
        bpm: 72,
        message: "",
      },
      {
        id: 85,
        level: "Intermediário I",
        firstFinger: 4,
        stringNumber: "3",
        bpm: 74,
        message: "",
      },
      {
        id: 86,
        level: "Intermediário I",
        firstFinger: 0,
        stringNumber: "4",
        bpm: 74,
        message: "",
      },
      {
        id: 87,
        level: "Intermediário I",
        firstFinger: 1,
        stringNumber: "4",
        bpm: 76,
        message: "",
      },
      {
        id: 88,
        level: "Intermediário I",
        firstFinger: 2,
        stringNumber: "4",
        bpm: 78,
        message: "",
      },
      {
        id: 89,
        level: "Intermediário II",
        firstFinger: 3,
        stringNumber: "4",
        bpm: 80,
        message: "",
      },
      {
        id: 90,
        level: "Intermediário II",
        firstFinger: 4,
        stringNumber: "4",
        bpm: 82,
        message: "",
      },
      {
        id: 91,
        level: "Intermediário II",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 82,
        message: "",
      },
      {
        id: 92,
        level: "Intermediário II",
        firstFinger: 1,
        stringNumber: "2",
        bpm: 84,
        message: "",
      },
      {
        id: 93,
        level: "Intermediário II",
        firstFinger: 2,
        stringNumber: "3",
        bpm: 88,
        message: "",
      },
      {
        id: 94,
        level: "Intermediário II",
        firstFinger: 3,
        stringNumber: "4",
        bpm: 90,
        message: "",
      },
      {
        id: 95,
        level: "Intermediário II",
        firstFinger: 4,
        stringNumber: "1",
        bpm: 92,
        message: "",
      },
      {
        id: 96,
        level: "Intermediário II",
        firstFinger: 0,
        stringNumber: "2",
        bpm: 94,
        message: "",
      },
      {
        id: 97,
        level: "Intermediário II",
        firstFinger: 1,
        stringNumber: "3",
        bpm: 96,
        message: "",
      },
      {
        id: 98,
        level: "Intermediário II",
        firstFinger: 2,
        stringNumber: "4",
        bpm: 98,
        message: "",
      },
      {
        id: 99,
        level: "Intermediário II",
        firstFinger: 3,
        stringNumber: "4",
        bpm: 100,
        message: "",
      },
      {
        id: 100,
        level: "Intermediário I",
        firstFinger: 4,
        stringNumber: "4",
        bpm: 100,
        message:
          "Você pegou o jeito! Vamos tentar com várias cordas? Ganhou o quinto troféu",
      },
      {
        id: 101,
        level: "Intermediário II",
        firstFinger: 0,
        stringNumber: "downToUp",
        bpm: 60,
        message: "",
      },
      {
        id: 102,
        level: "Intermediário II",
        firstFinger: 0,
        stringNumber: "downToUp",
        bpm: 60,
        message: "",
      },
      {
        id: 103,
        level: "Intermediário II",
        firstFinger: 1,
        stringNumber: "downToUp",
        bpm: 60,
        message: "",
      },
      {
        id: 104,
        level: "Intermediário II",
        firstFinger: 1,
        stringNumber: "downToUp",
        bpm: 60,
        message: "",
      },
      {
        id: 105,
        level: "Intermediário II",
        firstFinger: 2,
        stringNumber: "downToUp",
        bpm: 60,
        message: "",
      },
      {
        id: 106,
        level: "Intermediário II",
        firstFinger: 2,
        stringNumber: "downToUp",
        bpm: 60,
        message: "",
      },
      {
        id: 107,
        level: "Intermediário II",
        firstFinger: 3,
        stringNumber: "downToUp",
        bpm: 60,
        message: "",
      },
      {
        id: 108,
        level: "Intermediário II",
        firstFinger: 3,
        stringNumber: "downToUp",
        bpm: 60,
        message: "",
      },
      {
        id: 109,
        level: "Intermediário II",
        firstFinger: 4,
        stringNumber: "downToUp",
        bpm: 60,
        message: "",
      },
      {
        id: 110,
        level: "Intermediário II",
        firstFinger: 4,
        stringNumber: "downToUp",
        bpm: 60,
        message: "",
      },
      {
        id: 111,
        level: "Intermediário II",
        firstFinger: 0,
        stringNumber: "upToDown",
        bpm: 60,
        message: "",
      },
      {
        id: 112,
        level: "Intermediário II",
        firstFinger: 0,
        stringNumber: "upToDown",
        bpm: 60,
        message: "",
      },
      {
        id: 113,
        level: "Intermediário II",
        firstFinger: 1,
        stringNumber: "upToDown",
        bpm: 60,
        message: "",
      },
      {
        id: 114,
        level: "Intermediário II",
        firstFinger: 1,
        stringNumber: "upToDown",
        bpm: 60,
        message: "",
      },
      {
        id: 115,
        level: "Intermediário II",
        firstFinger: 2,
        stringNumber: "upToDown",
        bpm: 60,
        message: "",
      },
      {
        id: 116,
        level: "Intermediário II",
        firstFinger: 2,
        stringNumber: "upToDown",
        bpm: 60,
        message: "",
      },
      {
        id: 117,
        level: "Intermediário II",
        firstFinger: 3,
        stringNumber: "upToDown",
        bpm: 60,
        message: "",
      },
      {
        id: 118,
        level: "Intermediário II",
        firstFinger: 3,
        stringNumber: "upToDown",
        bpm: 60,
        message: "",
      },
      {
        id: 119,
        level: "Intermediário II",
        firstFinger: 4,
        stringNumber: "upToDown",
        bpm: 60,
        message: "",
      },
      {
        id: 120,
        level: "Intermediário II",
        firstFinger: 4,
        stringNumber: "upToDown",
        bpm: 60,
        message: "",
      },
      {
        id: 121,
        level: "Intermediário II",
        firstFinger: 0,
        stringNumber: "downToUp",
        bpm: 62,
        message: "",
      },
      {
        id: 122,
        level: "Intermediário II",
        firstFinger: 1,
        stringNumber: "upToDown",
        bpm: 64,
        message: "",
      },
      {
        id: 123,
        level: "Intermediário II",
        firstFinger: 2,
        stringNumber: "downToUp",
        bpm: 66,
        message: "",
      },
      {
        id: 124,
        level: "Intermediário II",
        firstFinger: 3,
        stringNumber: "upToDown",
        bpm: 68,
        message: "",
      },
      {
        id: 125,
        level: "Intermediário II",
        firstFinger: 4,
        stringNumber: "downToUp",
        bpm: 70,
        message: "",
      },
      {
        id: 126,
        level: "Intermediário II",
        firstFinger: 0,
        stringNumber: "upToDown",
        bpm: 72,
        message: "",
      },
      {
        id: 127,
        level: "Intermediário II",
        firstFinger: 1,
        stringNumber: "downToUp",
        bpm: 74,
        message: "",
      },
      {
        id: 128,
        level: "Intermediário II",
        firstFinger: 2,
        stringNumber: "upToDown",
        bpm: 76,
        message: "",
      },
      {
        id: 129,
        level: "Intermediário II",
        firstFinger: 3,
        stringNumber: "downToUp",
        bpm: 78,
        message: "",
      },
      {
        id: 130,
        level: "Intermediário II",
        firstFinger: 4,
        stringNumber: "upToDown",
        bpm: 80,
        message: "",
      },
      {
        id: 131,
        level: "Intermediário II",
        firstFinger: 0,
        stringNumber: "downToUp",
        bpm: 82,
        message: "",
      },
      {
        id: 132,
        level: "Intermediário II",
        firstFinger: 1,
        stringNumber: "upToDown",
        bpm: 84,
        message: "",
      },
      {
        id: 133,
        level: "Intermediário II",
        firstFinger: 2,
        stringNumber: "downToUp",
        bpm: 86,
        message: "",
      },
      {
        id: 134,
        level: "Intermediário II",
        firstFinger: 3,
        stringNumber: "upToDown",
        bpm: 88,
        message: "",
      },
      {
        id: 135,
        level: "Intermediário II",
        firstFinger: 4,
        stringNumber: "downToUp",
        bpm: 90,
        message: "",
      },
      {
        id: 136,
        level: "Intermediário II",
        firstFinger: 0,
        stringNumber: "upToDown",
        bpm: 92,
        message: "",
      },
      {
        id: 137,
        level: "Intermediário II",
        firstFinger: 1,
        stringNumber: "downToUp",
        bpm: 94,
        message: "",
      },
      {
        id: 138,
        level: "Intermediário II",
        firstFinger: 2,
        stringNumber: "upToDown",
        bpm: 96,
        message: "",
      },
      {
        id: 139,
        level: "Intermediário II",
        firstFinger: 3,
        stringNumber: "downToUp",
        bpm: 98,
        message: "",
      },
      {
        id: 140,
        level: "Intermediário II",
        firstFinger: 4,
        stringNumber: "upToDown",
        bpm: 100,
        message: "Você está ficando fera! Ganhou o sexto troféu!",
      },
      {
        id: 141,
        level: "Avançado I",
        firstFinger: 0,
        stringNumber: "downToUp",
        bpm: 102,
        message: "",
      },
      {
        id: 142,
        level: "Avançado I",
        firstFinger: 1,
        stringNumber: "upToDown",
        bpm: 104,
        message: "",
      },
      {
        id: 143,
        level: "Avançado I",
        firstFinger: 2,
        stringNumber: "downToUp",
        bpm: 106,
        message: "",
      },
      {
        id: 144,
        level: "Avançado I",
        firstFinger: 3,
        stringNumber: "upToDown",
        bpm: 108,
        message: "",
      },
      {
        id: 145,
        level: "Avançado I",
        firstFinger: 4,
        stringNumber: "downToUp",
        bpm: 110,
        message: "",
      },
      {
        id: 146,
        level: "Avançado I",
        firstFinger: 0,
        stringNumber: "upToDown",
        bpm: 112,
        message: "",
      },
      {
        id: 147,
        level: "Avançado I",
        firstFinger: 1,
        stringNumber: "downToUp",
        bpm: 114,
        message: "",
      },
      {
        id: 148,
        level: "Avançado I",
        firstFinger: 2,
        stringNumber: "upToDown",
        bpm: 116,
        message: "",
      },
      {
        id: 149,
        level: "Avançado I",
        firstFinger: 3,
        stringNumber: "downToUp",
        bpm: 118,
        message: "",
      },
      {
        id: 150,
        level: "Avançado I",
        firstFinger: 4,
        stringNumber: "upToDown",
        bpm: 120,
        message: "",
      },
      {
        id: 151,
        level: "Avançado I",
        firstFinger: 0,
        stringNumber: "downToUp",
        bpm: 122,
        message: "",
      },
      {
        id: 152,
        level: "Avançado I",
        firstFinger: 1,
        stringNumber: "upToDown",
        bpm: 124,
        message: "",
      },
      {
        id: 153,
        level: "Avançado I",
        firstFinger: 2,
        stringNumber: "downToUp",
        bpm: 126,
        message: "",
      },
      {
        id: 154,
        level: "Avançado I",
        firstFinger: 3,
        stringNumber: "upToDown",
        bpm: 128,
        message: "",
      },
      {
        id: 155,
        level: "Avançado I",
        firstFinger: 4,
        stringNumber: "downToUp",
        bpm: 130,
        message: "",
      },
      {
        id: 156,
        level: "Avançado I",
        firstFinger: 0,
        stringNumber: "upToDown",
        bpm: 132,
        message: "",
      },
      {
        id: 157,
        level: "Avançado I",
        firstFinger: 1,
        stringNumber: "downToUp",
        bpm: 134,
        message: "",
      },
      {
        id: 158,
        level: "Avançado I",
        firstFinger: 2,
        stringNumber: "upToDown",
        bpm: 136,
        message: "",
      },
      {
        id: 159,
        level: "Avançado I",
        firstFinger: 3,
        stringNumber: "downToUp",
        bpm: 138,
        message: "",
      },
      {
        id: 160,
        level: "Avançado I",
        firstFinger: 4,
        stringNumber: "upToDown",
        bpm: 140,
        message: "",
      },
      {
        id: 161,
        level: "Avançado I",
        firstFinger: 0,
        stringNumber: "downToUp",
        bpm: 142,
        message: "",
      },
      {
        id: 162,
        level: "Avançado I",
        firstFinger: 1,
        stringNumber: "upToDown",
        bpm: 144,
        message: "",
      },
      {
        id: 163,
        level: "Avançado I",
        firstFinger: 2,
        stringNumber: "downToUp",
        bpm: 146,
        message: "",
      },
      {
        id: 164,
        level: "Avançado I",
        firstFinger: 3,
        stringNumber: "upToDown",
        bpm: 148,
        message: "",
      },
      {
        id: 165,
        level: "Avançado I",
        firstFinger: 4,
        stringNumber: "downToUp",
        bpm: 150,
        message: "Ganhou o sétimo troféu!",
      },
      {
        id: 166,
        level: "Avançado II",
        firstFinger: 0,
        stringNumber: "upToDown",
        bpm: 152,
        message: "",
      },
      {
        id: 167,
        level: "Avançado II",
        firstFinger: 1,
        stringNumber: "downToUp",
        bpm: 154,
        message: "",
      },
      {
        id: 168,
        level: "Avançado II",
        firstFinger: 2,
        stringNumber: "upToDown",
        bpm: 156,
        message: "",
      },
      {
        id: 169,
        level: "Avançado II",
        firstFinger: 3,
        stringNumber: "downToUp",
        bpm: 158,
        message: "",
      },
      {
        id: 170,
        level: "Avançado II",
        firstFinger: 4,
        stringNumber: "upToDown",
        bpm: 160,
        message: "",
      },
      {
        id: 171,
        level: "Avançado II",
        firstFinger: 0,
        stringNumber: "downToUp",
        bpm: 162,
        message: "",
      },
      {
        id: 172,
        level: "Avançado II",
        firstFinger: 1,
        stringNumber: "upToDown",
        bpm: 164,
        message: "",
      },
      {
        id: 173,
        level: "Avançado II",
        firstFinger: 2,
        stringNumber: "downToUp",
        bpm: 166,
        message: "",
      },
      {
        id: 174,
        level: "Avançado II",
        firstFinger: 3,
        stringNumber: "upToDown",
        bpm: 168,
        message: "",
      },
      {
        id: 175,
        level: "Avançado II",
        firstFinger: 4,
        stringNumber: "downToUp",
        bpm: 170,
        message: "",
      },
      {
        id: 176,
        level: "Avançado II",
        firstFinger: 0,
        stringNumber: "upToDown",
        bpm: 172,
        message: "",
      },
      {
        id: 177,
        level: "Avançado II",
        firstFinger: 1,
        stringNumber: "downToUp",
        bpm: 174,
        message: "",
      },
      {
        id: 178,
        level: "Avançado II",
        firstFinger: 2,
        stringNumber: "upToDown",
        bpm: 176,
        message: "",
      },
      {
        id: 179,
        level: "Avançado II",
        firstFinger: 3,
        stringNumber: "downToUp",
        bpm: 178,
        message: "",
      },
      {
        id: 180,
        level: "Avançado II",
        firstFinger: 4,
        stringNumber: "upToDown",
        bpm: 180,
        message: "",
      },
      {
        id: 181,
        level: "Avançado II",
        firstFinger: 0,
        stringNumber: "downToUp",
        bpm: 182,
        message: "",
      },
      {
        id: 182,
        level: "Avançado II",
        firstFinger: 1,
        stringNumber: "upToDown",
        bpm: 184,
        message: "",
      },
      {
        id: 183,
        level: "Avançado II",
        firstFinger: 2,
        stringNumber: "downToUp",
        bpm: 186,
        message: "",
      },
      {
        id: 184,
        level: "Avançado II",
        firstFinger: 3,
        stringNumber: "upToDown",
        bpm: 188,
        message: "",
      },
      {
        id: 185,
        level: "Avançado II",
        firstFinger: 4,
        stringNumber: "downToUp",
        bpm: 190,
        message: "",
      },
      {
        id: 186,
        level: "Avançado II",
        firstFinger: 0,
        stringNumber: "upToDown",
        bpm: 192,
        message: "",
      },
      {
        id: 187,
        level: "Avançado II",
        firstFinger: 1,
        stringNumber: "downToUp",
        bpm: 194,
        message: "",
      },
      {
        id: 188,
        level: "Avançado II",
        firstFinger: 2,
        stringNumber: "upToDown",
        bpm: 196,
        message: "",
      },
      {
        id: 189,
        level: "Avançado II",
        firstFinger: 3,
        stringNumber: "downToUp",
        bpm: 198,
        message: "",
      },
      {
        id: 190,
        level: "Avançado II",
        firstFinger: 4,
        stringNumber: "upToDown",
        bpm: 200,
        message:
          "Você zerou o jogo! Parabéns! Ganhou o mega troféu e seu nome no hall de usuário mestre!",
      },
    ],
    sixStrings: [
      {
        id: 1,
        level: "tutorial",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 30,
        message: "",
      },
      {
        id: 2,
        level: "tutorial",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 30,
        message: "",
      },
      {
        id: 3,
        level: "tutorial",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 32,
        message: "",
      },
      {
        id: 4,
        level: "tutorial",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 32,
        message: "",
      },
      {
        id: 5,
        level: "tutorial",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 34,
        message: "",
      },
      {
        id: 6,
        level: "tutorial",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 34,
        message: "",
      },
      {
        id: 7,
        level: "tutorial",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 36,
        message: "",
      },
      {
        id: 8,
        level: "tutorial",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 36,
        message: "",
      },
      {
        id: 9,
        level: "tutorial",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 38,
        message: "",
      },
      {
        id: 10,
        level: "tutorial",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 38,
        message: "Você concluiu o tutorial! Ganhou o 1º troféu!",
      },
      {
        id: 11,
        level: "Iniciante",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 40,
        message: "",
      },
      {
        id: 12,
        level: "Iniciante",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 42,
        message: "",
      },
      {
        id: 13,
        level: "Iniciante",
        firstFinger: 1,
        stringNumber: "1",
        bpm: 40,
        message: "",
      },
      {
        id: 14,
        level: "Iniciante",
        firstFinger: 1,
        stringNumber: "1",
        bpm: 42,
        message: "",
      },
      {
        id: 15,
        level: "Iniciante",
        firstFinger: 2,
        stringNumber: "1",
        bpm: 42,
        message: "",
      },
      {
        id: 16,
        level: "Iniciante",
        firstFinger: 2,
        stringNumber: "1",
        bpm: 44,
        message: "",
      },
      {
        id: 17,
        level: "Iniciante",
        firstFinger: 3,
        stringNumber: "1",
        bpm: 44,
        message: "",
      },
      {
        id: 18,
        level: "Iniciante",
        firstFinger: 3,
        stringNumber: "1",
        bpm: 46,
        message: "",
      },
      {
        id: 19,
        level: "Iniciante",
        firstFinger: 4,
        stringNumber: "1",
        bpm: 46,
        message: "",
      },
      {
        id: 20,
        level: "Iniciante",
        firstFinger: 4,
        stringNumber: "1",
        bpm: 48,
        message:
          "Você exercitou todos os dedos. Agora vamos tentar o mesmo com outras cordas! Ganhou o 2º troféu!",
      },
      {
        id: 21,
        level: "Básico I",
        firstFinger: 0,
        stringNumber: "2",
        bpm: 40,
        message: "",
      },
      {
        id: 22,
        level: "Básico I",
        firstFinger: 0,
        stringNumber: "2",
        bpm: 42,
        message: "",
      },
      {
        id: 23,
        level: "Básico I",
        firstFinger: 1,
        stringNumber: "2",
        bpm: 40,
        message: "",
      },
      {
        id: 24,
        level: "Básico I",
        firstFinger: 1,
        stringNumber: "2",
        bpm: 42,
        message: "",
      },
      {
        id: 25,
        level: "Básico I",
        firstFinger: 2,
        stringNumber: "2",
        bpm: 42,
        message: "",
      },
      {
        id: 26,
        level: "Básico I",
        firstFinger: 2,
        stringNumber: "2",
        bpm: 44,
        message: "",
      },
      {
        id: 27,
        level: "Básico I",
        firstFinger: 3,
        stringNumber: "2",
        bpm: 44,
        message: "",
      },
      {
        id: 28,
        level: "Básico I",
        firstFinger: 3,
        stringNumber: "2",
        bpm: 46,
        message: "",
      },
      {
        id: 29,
        level: "Básico I",
        firstFinger: 4,
        stringNumber: "2",
        bpm: 46,
        message: "",
      },
      {
        id: 30,
        level: "Básico I",
        firstFinger: 4,
        stringNumber: "2",
        bpm: 48,
        message: "Você exercitou a segunda corda!",
      },
      {
        id: 31,
        level: "Básico I",
        firstFinger: 0,
        stringNumber: "3",
        bpm: 40,
        message: "",
      },
      {
        id: 32,
        level: "Básico I",
        firstFinger: 0,
        stringNumber: "3",
        bpm: 42,
        message: "",
      },
      {
        id: 33,
        level: "Básico I",
        firstFinger: 1,
        stringNumber: "3",
        bpm: 40,
        message: "",
      },
      {
        id: 34,
        level: "Básico I",
        firstFinger: 1,
        stringNumber: "3",
        bpm: 42,
        message: "",
      },
      {
        id: 35,
        level: "Básico I",
        firstFinger: 2,
        stringNumber: "3",
        bpm: 42,
        message: "",
      },
      {
        id: 36,
        level: "Básico I",
        firstFinger: 2,
        stringNumber: "3",
        bpm: 44,
        message: "",
      },
      {
        id: 37,
        level: "Básico I",
        firstFinger: 3,
        stringNumber: "3",
        bpm: 44,
        message: "",
      },
      {
        id: 38,
        level: "Básico I",
        firstFinger: 3,
        stringNumber: "3",
        bpm: 46,
        message: "",
      },
      {
        id: 39,
        level: "Básico I",
        firstFinger: 4,
        stringNumber: "3",
        bpm: 46,
        message: "",
      },
      {
        id: 40,
        level: "Básico I",
        firstFinger: 4,
        stringNumber: "3",
        bpm: 48,
        message: "Você exercitou a terceira corda! Ganhou o terceiro troféu!",
      },
      {
        id: 41,
        level: "Básico II",
        firstFinger: 0,
        stringNumber: "4",
        bpm: 40,
        message: "",
      },
      {
        id: 42,
        level: "Básico II",
        firstFinger: 0,
        stringNumber: "4",
        bpm: 42,
        message: "",
      },
      {
        id: 43,
        level: "Básico II",
        firstFinger: 1,
        stringNumber: "4",
        bpm: 40,
        message: "",
      },
      {
        id: 44,
        level: "Básico II",
        firstFinger: 1,
        stringNumber: "4",
        bpm: 42,
        message: "",
      },
      {
        id: 45,
        level: "Básico II",
        firstFinger: 2,
        stringNumber: "4",
        bpm: 42,
        message: "",
      },
      {
        id: 46,
        level: "Básico II",
        firstFinger: 2,
        stringNumber: "4",
        bpm: 44,
        message: "",
      },
      {
        id: 47,
        level: "Básico II",
        firstFinger: 3,
        stringNumber: "4",
        bpm: 44,
        message: "",
      },
      {
        id: 48,
        level: "Básico II",
        firstFinger: 3,
        stringNumber: "4",
        bpm: 46,
        message: "",
      },
      {
        id: 49,
        level: "Básico II",
        firstFinger: 4,
        stringNumber: "4",
        bpm: 46,
        message: "",
      },
      {
        id: 50,
        level: "Básico II",
        firstFinger: 4,
        stringNumber: "4",
        bpm: 48,
        message: "Você exercitou a quarta corda!",
      },
      {
        id: 51,
        level: "Básico II",
        firstFinger: 0,
        stringNumber: "5",
        bpm: 40,
        message: "",
      },
      {
        id: 52,
        level: "Básico II",
        firstFinger: 0,
        stringNumber: "5",
        bpm: 42,
        message: "",
      },
      {
        id: 53,
        level: "Básico II",
        firstFinger: 1,
        stringNumber: "5",
        bpm: 40,
        message: "",
      },
      {
        id: 54,
        level: "Básico II",
        firstFinger: 1,
        stringNumber: "5",
        bpm: 42,
        message: "",
      },
      {
        id: 55,
        level: "Básico II",
        firstFinger: 2,
        stringNumber: "5",
        bpm: 42,
        message: "",
      },
      {
        id: 56,
        level: "Básico II",
        firstFinger: 2,
        stringNumber: "5",
        bpm: 44,
        message: "",
      },
      {
        id: 57,
        level: "Básico II",
        firstFinger: 3,
        stringNumber: "5",
        bpm: 44,
        message: "",
      },
      {
        id: 58,
        level: "Básico II",
        firstFinger: 3,
        stringNumber: "5",
        bpm: 46,
        message: "",
      },
      {
        id: 59,
        level: "Básico II",
        firstFinger: 4,
        stringNumber: "5",
        bpm: 46,
        message: "",
      },
      {
        id: 60,
        level: "Básico II",
        firstFinger: 4,
        stringNumber: "5",
        bpm: 48,
        message: "Você exercitou a quinta corda!",
      },
      {
        id: 61,
        level: "Básico II",
        firstFinger: 0,
        stringNumber: "6",
        bpm: 40,
        message: "",
      },
      {
        id: 62,
        level: "Básico II",
        firstFinger: 0,
        stringNumber: "6",
        bpm: 42,
        message: "",
      },
      {
        id: 63,
        level: "Básico II",
        firstFinger: 1,
        stringNumber: "6",
        bpm: 40,
        message: "",
      },
      {
        id: 64,
        level: "Básico II",
        firstFinger: 1,
        stringNumber: "6",
        bpm: 42,
        message: "",
      },
      {
        id: 65,
        level: "Básico II",
        firstFinger: 2,
        stringNumber: "6",
        bpm: 42,
        message: "",
      },
      {
        id: 66,
        level: "Básico II",
        firstFinger: 2,
        stringNumber: "6",
        bpm: 44,
        message: "",
      },
      {
        id: 67,
        level: "Básico II",
        firstFinger: 3,
        stringNumber: "6",
        bpm: 44,
        message: "",
      },
      {
        id: 68,
        level: "Básico II",
        firstFinger: 3,
        stringNumber: "6",
        bpm: 46,
        message: "",
      },
      {
        id: 69,
        level: "Básico II",
        firstFinger: 4,
        stringNumber: "6",
        bpm: 46,
        message: "",
      },
      {
        id: 70,
        level: "Básico II",
        firstFinger: 4,
        stringNumber: "6",
        bpm: 48,
        message:
          "Você exercitou todas as cordas! Que tal dar uma acelerada? Ganhou o quarto troféu!",
      },
      {
        id: 71,
        level: "Intermediário I",
        firstFinger: 0,
        stringNumber: "1",
        bpm: 50,
        message: "",
      },
      {
        id: 72,
        level: "Intermediário I",
        firstFinger: 1,
        stringNumber: "1",
        bpm: 50,
        message: "",
      },
      {
        id: 73,
        level: "Intermediário I",
        firstFinger: 2,
        stringNumber: "1",
        bpm: 52,
        message: "",
      },
      {
        id: 74,
        level: "Intermediário I",
        firstFinger: 3,
        stringNumber: "1",
        bpm: 54,
        message: "",
      },
      {
        id: 75,
        level: "Intermediário I",
        firstFinger: 4,
        stringNumber: "1",
        bpm: 56,
        message: "",
      },
      {
        id: 76,
        level: "Intermediário I",
        firstFinger: 0,
        stringNumber: "2",
        bpm: 58,
        message: "",
      },
      {
        id: 77,
        level: "Intermediário I",
        firstFinger: 1,
        stringNumber: "2",
        bpm: 58,
        message: "",
      },
      {
        id: 78,
        level: "Intermediário I",
        firstFinger: 2,
        stringNumber: "2",
        bpm: 60,
        message: "",
      },
      {
        id: 79,
        level: "Intermediário I",
        firstFinger: 3,
        stringNumber: "2",
        bpm: 62,
        message: "",
      },
      {
        id: 80,
        level: "Intermediário I",
        firstFinger: 4,
        stringNumber: "2",
        bpm: 64,
        message: "",
      },
      {
        id: 81,
        level: "Intermediário I",
        firstFinger: 0,
        stringNumber: "3",
        bpm: 66,
        message: "",
      },
      {
        id: 82,
        level: "Intermediário I",
        firstFinger: 1,
        stringNumber: "3",
        bpm: 66,
        message: "",
      },
      {
        id: 83,
        level: "Intermediário I",
        firstFinger: 2,
        stringNumber: "3",
        bpm: 68,
        message: "",
      },
      {
        id: 84,
        level: "Intermediário I",
        firstFinger: 3,
        stringNumber: "3",
        bpm: 70,
        message: "",
      },
      {
        id: 85,
        level: "Intermediário I",
        firstFinger: 4,
        stringNumber: "3",
        bpm: 72,
        message: "",
      },
      {
        id: 86,
        level: "Intermediário I",
        firstFinger: 0,
        stringNumber: "4",
        bpm: 74,
        message: "",
      },
      {
        id: 87,
        level: "Intermediário I",
        firstFinger: 1,
        stringNumber: "4",
        bpm: 74,
        message: "",
      },
      {
        id: 88,
        level: "Intermediário I",
        firstFinger: 2,
        stringNumber: "4",
        bpm: 76,
        message: "",
      },
      {
        id: 89,
        level: "Intermediário I",
        firstFinger: 3,
        stringNumber: "4",
        bpm: 78,
        message: "",
      },
      {
        id: 90,
        level: "Intermediário I",
        firstFinger: 4,
        stringNumber: "4",
        bpm: 80,
        message: "",
      },
      {
        id: 91,
        level: "Intermediário I",
        firstFinger: 0,
        stringNumber: "5",
        bpm: 82,
        message: "",
      },
      {
        id: 92,
        level: "Intermediário I",
        firstFinger: 1,
        stringNumber: "5",
        bpm: 82,
        message: "",
      },
      {
        id: 93,
        level: "Intermediário I",
        firstFinger: 2,
        stringNumber: "5",
        bpm: 84,
        message: "",
      },
      {
        id: 94,
        level: "Intermediário I",
        firstFinger: 3,
        stringNumber: "5",
        bpm: 88,
        message: "",
      },
      {
        id: 95,
        level: "Intermediário I",
        firstFinger: 4,
        stringNumber: "5",
        bpm: 90,
        message: "",
      },
      {
        id: 96,
        level: "Intermediário I",
        firstFinger: 0,
        stringNumber: "6",
        bpm: 92,
        message: "",
      },
      {
        id: 97,
        level: "Intermediário I",
        firstFinger: 1,
        stringNumber: "6",
        bpm: 94,
        message: "",
      },
      {
        id: 98,
        level: "Intermediário I",
        firstFinger: 2,
        stringNumber: "6",
        bpm: 96,
        message: "",
      },
      {
        id: 99,
        level: "Intermediário I",
        firstFinger: 3,
        stringNumber: "6",
        bpm: 98,
        message: "",
      },
      {
        id: 100,
        level: "Intermediário I",
        firstFinger: 4,
        stringNumber: "6",
        bpm: 100,
        message:
          "Você pegou o jeito! Vamos tentar com várias cordas? Ganhou o quinto troféu",
      },
      {
        id: 101,
        level: "Intermediário II",
        firstFinger: 0,
        stringNumber: "downToUp",
        bpm: 60,
        message: "",
      },
      {
        id: 102,
        level: "Intermediário II",
        firstFinger: 0,
        stringNumber: "downToUp",
        bpm: 60,
        message: "",
      },
      {
        id: 103,
        level: "Intermediário II",
        firstFinger: 1,
        stringNumber: "downToUp",
        bpm: 60,
        message: "",
      },
      {
        id: 104,
        level: "Intermediário II",
        firstFinger: 1,
        stringNumber: "downToUp",
        bpm: 60,
        message: "",
      },
      {
        id: 105,
        level: "Intermediário II",
        firstFinger: 2,
        stringNumber: "downToUp",
        bpm: 60,
        message: "",
      },
      {
        id: 106,
        level: "Intermediário II",
        firstFinger: 2,
        stringNumber: "downToUp",
        bpm: 60,
        message: "",
      },
      {
        id: 107,
        level: "Intermediário II",
        firstFinger: 3,
        stringNumber: "downToUp",
        bpm: 60,
        message: "",
      },
      {
        id: 108,
        level: "Intermediário II",
        firstFinger: 3,
        stringNumber: "downToUp",
        bpm: 60,
        message: "",
      },
      {
        id: 109,
        level: "Intermediário II",
        firstFinger: 4,
        stringNumber: "downToUp",
        bpm: 60,
        message: "",
      },
      {
        id: 110,
        level: "Intermediário II",
        firstFinger: 4,
        stringNumber: "downToUp",
        bpm: 60,
        message: "",
      },
      {
        id: 111,
        level: "Intermediário II",
        firstFinger: 0,
        stringNumber: "upToDown",
        bpm: 60,
        message: "",
      },
      {
        id: 112,
        level: "Intermediário II",
        firstFinger: 0,
        stringNumber: "upToDown",
        bpm: 60,
        message: "",
      },
      {
        id: 113,
        level: "Intermediário II",
        firstFinger: 1,
        stringNumber: "upToDown",
        bpm: 60,
        message: "",
      },
      {
        id: 114,
        level: "Intermediário II",
        firstFinger: 1,
        stringNumber: "upToDown",
        bpm: 60,
        message: "",
      },
      {
        id: 115,
        level: "Intermediário II",
        firstFinger: 2,
        stringNumber: "upToDown",
        bpm: 60,
        message: "",
      },
      {
        id: 116,
        level: "Intermediário II",
        firstFinger: 2,
        stringNumber: "upToDown",
        bpm: 60,
        message: "",
      },
      {
        id: 117,
        level: "Intermediário II",
        firstFinger: 3,
        stringNumber: "upToDown",
        bpm: 60,
        message: "",
      },
      {
        id: 118,
        level: "Intermediário II",
        firstFinger: 3,
        stringNumber: "upToDown",
        bpm: 60,
        message: "",
      },
      {
        id: 119,
        level: "Intermediário II",
        firstFinger: 4,
        stringNumber: "upToDown",
        bpm: 60,
        message: "",
      },
      {
        id: 120,
        level: "Intermediário II",
        firstFinger: 4,
        stringNumber: "upToDown",
        bpm: 60,
        message: "",
      },
      {
        id: 121,
        level: "Intermediário II",
        firstFinger: 0,
        stringNumber: "downToUp",
        bpm: 62,
        message: "",
      },
      {
        id: 122,
        level: "Intermediário II",
        firstFinger: 1,
        stringNumber: "upToDown",
        bpm: 64,
        message: "",
      },
      {
        id: 123,
        level: "Intermediário II",
        firstFinger: 2,
        stringNumber: "downToUp",
        bpm: 66,
        message: "",
      },
      {
        id: 124,
        level: "Intermediário II",
        firstFinger: 3,
        stringNumber: "upToDown",
        bpm: 68,
        message: "",
      },
      {
        id: 125,
        level: "Intermediário II",
        firstFinger: 4,
        stringNumber: "downToUp",
        bpm: 70,
        message: "",
      },
      {
        id: 126,
        level: "Intermediário II",
        firstFinger: 0,
        stringNumber: "upToDown",
        bpm: 72,
        message: "",
      },
      {
        id: 127,
        level: "Intermediário II",
        firstFinger: 1,
        stringNumber: "downToUp",
        bpm: 74,
        message: "",
      },
      {
        id: 128,
        level: "Intermediário II",
        firstFinger: 2,
        stringNumber: "upToDown",
        bpm: 76,
        message: "",
      },
      {
        id: 129,
        level: "Intermediário II",
        firstFinger: 3,
        stringNumber: "downToUp",
        bpm: 78,
        message: "",
      },
      {
        id: 130,
        level: "Intermediário II",
        firstFinger: 4,
        stringNumber: "upToDown",
        bpm: 80,
        message: "",
      },
      {
        id: 131,
        level: "Intermediário II",
        firstFinger: 0,
        stringNumber: "downToUp",
        bpm: 82,
        message: "",
      },
      {
        id: 132,
        level: "Intermediário II",
        firstFinger: 1,
        stringNumber: "upToDown",
        bpm: 84,
        message: "",
      },
      {
        id: 133,
        level: "Intermediário II",
        firstFinger: 2,
        stringNumber: "downToUp",
        bpm: 86,
        message: "",
      },
      {
        id: 134,
        level: "Intermediário II",
        firstFinger: 3,
        stringNumber: "upToDown",
        bpm: 88,
        message: "",
      },
      {
        id: 135,
        level: "Intermediário II",
        firstFinger: 4,
        stringNumber: "downToUp",
        bpm: 90,
        message: "",
      },
      {
        id: 136,
        level: "Intermediário II",
        firstFinger: 0,
        stringNumber: "upToDown",
        bpm: 92,
        message: "",
      },
      {
        id: 137,
        level: "Intermediário II",
        firstFinger: 1,
        stringNumber: "downToUp",
        bpm: 94,
        message: "",
      },
      {
        id: 138,
        level: "Intermediário II",
        firstFinger: 2,
        stringNumber: "upToDown",
        bpm: 96,
        message: "",
      },
      {
        id: 139,
        level: "Intermediário II",
        firstFinger: 3,
        stringNumber: "downToUp",
        bpm: 98,
        message: "",
      },
      {
        id: 140,
        level: "Intermediário II",
        firstFinger: 4,
        stringNumber: "upToDown",
        bpm: 100,
        message: "Você está ficando fera! Ganhou o sexto troféu!",
      },
      {
        id: 141,
        level: "Avançado I",
        firstFinger: 0,
        stringNumber: "downToUp",
        bpm: 102,
        message: "",
      },
      {
        id: 142,
        level: "Avançado I",
        firstFinger: 1,
        stringNumber: "upToDown",
        bpm: 104,
        message: "",
      },
      {
        id: 143,
        level: "Avançado I",
        firstFinger: 2,
        stringNumber: "downToUp",
        bpm: 106,
        message: "",
      },
      {
        id: 144,
        level: "Avançado I",
        firstFinger: 3,
        stringNumber: "upToDown",
        bpm: 108,
        message: "",
      },
      {
        id: 145,
        level: "Avançado I",
        firstFinger: 4,
        stringNumber: "downToUp",
        bpm: 110,
        message: "",
      },
      {
        id: 146,
        level: "Avançado I",
        firstFinger: 0,
        stringNumber: "upToDown",
        bpm: 112,
        message: "",
      },
      {
        id: 147,
        level: "Avançado I",
        firstFinger: 1,
        stringNumber: "downToUp",
        bpm: 114,
        message: "",
      },
      {
        id: 148,
        level: "Avançado I",
        firstFinger: 2,
        stringNumber: "upToDown",
        bpm: 116,
        message: "",
      },
      {
        id: 149,
        level: "Avançado I",
        firstFinger: 3,
        stringNumber: "downToUp",
        bpm: 118,
        message: "",
      },
      {
        id: 150,
        level: "Avançado I",
        firstFinger: 4,
        stringNumber: "upToDown",
        bpm: 120,
        message: "",
      },
      {
        id: 151,
        level: "Avançado I",
        firstFinger: 0,
        stringNumber: "downToUp",
        bpm: 122,
        message: "",
      },
      {
        id: 152,
        level: "Avançado I",
        firstFinger: 1,
        stringNumber: "upToDown",
        bpm: 124,
        message: "",
      },
      {
        id: 153,
        level: "Avançado I",
        firstFinger: 2,
        stringNumber: "downToUp",
        bpm: 126,
        message: "",
      },
      {
        id: 154,
        level: "Avançado I",
        firstFinger: 3,
        stringNumber: "upToDown",
        bpm: 128,
        message: "",
      },
      {
        id: 155,
        level: "Avançado I",
        firstFinger: 4,
        stringNumber: "downToUp",
        bpm: 130,
        message: "",
      },
      {
        id: 156,
        level: "Avançado I",
        firstFinger: 0,
        stringNumber: "upToDown",
        bpm: 132,
        message: "",
      },
      {
        id: 157,
        level: "Avançado I",
        firstFinger: 1,
        stringNumber: "downToUp",
        bpm: 134,
        message: "",
      },
      {
        id: 158,
        level: "Avançado I",
        firstFinger: 2,
        stringNumber: "upToDown",
        bpm: 136,
        message: "",
      },
      {
        id: 159,
        level: "Avançado I",
        firstFinger: 3,
        stringNumber: "downToUp",
        bpm: 138,
        message: "",
      },
      {
        id: 160,
        level: "Avançado I",
        firstFinger: 4,
        stringNumber: "upToDown",
        bpm: 140,
        message: "",
      },
      {
        id: 161,
        level: "Avançado I",
        firstFinger: 0,
        stringNumber: "downToUp",
        bpm: 142,
        message: "",
      },
      {
        id: 162,
        level: "Avançado I",
        firstFinger: 1,
        stringNumber: "upToDown",
        bpm: 144,
        message: "",
      },
      {
        id: 163,
        level: "Avançado I",
        firstFinger: 2,
        stringNumber: "downToUp",
        bpm: 146,
        message: "",
      },
      {
        id: 164,
        level: "Avançado I",
        firstFinger: 3,
        stringNumber: "upToDown",
        bpm: 148,
        message: "",
      },
      {
        id: 165,
        level: "Avançado I",
        firstFinger: 4,
        stringNumber: "downToUp",
        bpm: 150,
        message: "Ganhou o sétimo troféu!",
      },
      {
        id: 166,
        level: "Avançado II",
        firstFinger: 0,
        stringNumber: "upToDown",
        bpm: 152,
        message: "",
      },
      {
        id: 167,
        level: "Avançado II",
        firstFinger: 1,
        stringNumber: "downToUp",
        bpm: 154,
        message: "",
      },
      {
        id: 168,
        level: "Avançado II",
        firstFinger: 2,
        stringNumber: "upToDown",
        bpm: 156,
        message: "",
      },
      {
        id: 169,
        level: "Avançado II",
        firstFinger: 3,
        stringNumber: "downToUp",
        bpm: 158,
        message: "",
      },
      {
        id: 170,
        level: "Avançado II",
        firstFinger: 4,
        stringNumber: "upToDown",
        bpm: 160,
        message: "",
      },
      {
        id: 171,
        level: "Avançado II",
        firstFinger: 0,
        stringNumber: "downToUp",
        bpm: 162,
        message: "",
      },
      {
        id: 172,
        level: "Avançado II",
        firstFinger: 1,
        stringNumber: "upToDown",
        bpm: 164,
        message: "",
      },
      {
        id: 173,
        level: "Avançado II",
        firstFinger: 2,
        stringNumber: "downToUp",
        bpm: 166,
        message: "",
      },
      {
        id: 174,
        level: "Avançado II",
        firstFinger: 3,
        stringNumber: "upToDown",
        bpm: 168,
        message: "",
      },
      {
        id: 175,
        level: "Avançado II",
        firstFinger: 4,
        stringNumber: "downToUp",
        bpm: 170,
        message: "",
      },
      {
        id: 176,
        level: "Avançado II",
        firstFinger: 0,
        stringNumber: "upToDown",
        bpm: 172,
        message: "",
      },
      {
        id: 177,
        level: "Avançado II",
        firstFinger: 1,
        stringNumber: "downToUp",
        bpm: 174,
        message: "",
      },
      {
        id: 178,
        level: "Avançado II",
        firstFinger: 2,
        stringNumber: "upToDown",
        bpm: 176,
        message: "",
      },
      {
        id: 179,
        level: "Avançado II",
        firstFinger: 3,
        stringNumber: "downToUp",
        bpm: 178,
        message: "",
      },
      {
        id: 180,
        level: "Avançado II",
        firstFinger: 4,
        stringNumber: "upToDown",
        bpm: 180,
        message: "",
      },
      {
        id: 181,
        level: "Avançado II",
        firstFinger: 0,
        stringNumber: "downToUp",
        bpm: 182,
        message: "",
      },
      {
        id: 182,
        level: "Avançado II",
        firstFinger: 1,
        stringNumber: "upToDown",
        bpm: 184,
        message: "",
      },
      {
        id: 183,
        level: "Avançado II",
        firstFinger: 2,
        stringNumber: "downToUp",
        bpm: 186,
        message: "",
      },
      {
        id: 184,
        level: "Avançado II",
        firstFinger: 3,
        stringNumber: "upToDown",
        bpm: 188,
        message: "",
      },
      {
        id: 185,
        level: "Avançado II",
        firstFinger: 4,
        stringNumber: "downToUp",
        bpm: 190,
        message: "",
      },
      {
        id: 186,
        level: "Avançado II",
        firstFinger: 0,
        stringNumber: "upToDown",
        bpm: 192,
        message: "",
      },
      {
        id: 187,
        level: "Avançado II",
        firstFinger: 1,
        stringNumber: "downToUp",
        bpm: 194,
        message: "",
      },
      {
        id: 188,
        level: "Avançado II",
        firstFinger: 2,
        stringNumber: "upToDown",
        bpm: 196,
        message: "",
      },
      {
        id: 189,
        level: "Avançado II",
        firstFinger: 3,
        stringNumber: "downToUp",
        bpm: 198,
        message: "",
      },
      {
        id: 190,
        level: "Avançado II",
        firstFinger: 4,
        stringNumber: "upToDown",
        bpm: 200,
        message:
          "Você zerou o jogo! Parabéns! Ganhou o mega troféu e seu nome no hall de usuário mestre!",
      },
    ],
  };

  /**
   * Retrieves lessons based on the specified instrument.
   *
   * @param {string} instrument - The type of instrument for which to get lessons.
   * @returns {Array} An array of lessons corresponding to the instrument type.
   *                   - If the instrument is 'bass' or 'cavaco', returns lessons for four-string instruments.
   *                   - If the instrument is 'acoustic-guitar' or 'electric-guitar', returns lessons for six-string instruments.
   *                   - For any other instrument, returns an array with a single empty lesson.
   */
  function getLessons(instrument: string) {
    switch (true) {
      case instrument === "bass" || instrument === "cavaco":
        return lessons.fourStrings;
      case instrument === "acoustic-guitar" || instrument === "eletric-guitar":
        return lessons.sixStrings;
      default:
        return [getEmptyLesson()];
    }
  }

  /**
   * Retrieves a lesson based on the provided instrument and lesson ID.
   *
   * @param {number} id - The unique identifier of the lesson.
   * @param {string} instrument - The type of instrument for which the lesson is intended.
   * @returns {Lesson | undefined} The lesson object if found, otherwise an empty lesson object.
   */
  function getLesson(id: number, instrument: string) {
    switch (true) {
      case instrument === "bass" || instrument === "cavaco":
        return lessons.fourStrings.find((lesson) => lesson.id === id);
      case instrument === "acoustic-guitar" || instrument === "eletric-guitar":
        return lessons.sixStrings.find((lesson) => lesson.id === id);
        break;
      default:
        break;
    }
    return getEmptyLesson();
  }

  /**
   * Returns an object representing an empty lesson with default values.
   *
   * @returns {Object} An object with the following properties:
   * - `id` {number}: The ID of the lesson, default is 0.
   * - `level` {string}: The level of the lesson, default is an empty string.
   * - `firstFinger` {number}: The first finger position, default is 0.
   * - `stringNumber` {string}: The string number, default is an empty string.
   * - `bpm` {number}: The beats per minute, default is 0.
   * - `message` {string}: A message associated with the lesson, default is an empty string.
   */
  function getEmptyLesson() {
    return {
      id: 0,
      level: "",
      firstFinger: 0,
      stringNumber: "",
      bpm: 0,
      message: "",
    };
  }

  return {
    getLessons,
    getLesson,
    getEmptyLesson,
  };
};
