import type { Lesson } from './model/lesson'

export const useLessons = () => {
	const lessons = {
		fourStrings: [
			{
				id: 1,
				level: 'tutorial',
				firstFinger: 1,
				stringNumber: '1',
				bpm: 30,
				message: '',
			},
			{
				id: 2,
				level: 'tutorial',
				firstFinger: 1,
				stringNumber: '1',
				bpm: 30,
				message: '',
			},
			{
				id: 3,
				level: 'tutorial',
				firstFinger: 1,
				stringNumber: '1',
				bpm: 32,
				message: '',
			},
			{
				id: 4,
				level: 'tutorial',
				firstFinger: 1,
				stringNumber: '1',
				bpm: 32,
				message: '',
			},
			{
				id: 5,
				level: 'tutorial',
				firstFinger: 1,
				stringNumber: '1',
				bpm: 34,
				message: '',
			},
			{
				id: 6,
				level: 'tutorial',
				firstFinger: 1,
				stringNumber: '1',
				bpm: 34,
				message: '',
			},
			{
				id: 7,
				level: 'tutorial',
				firstFinger: 1,
				stringNumber: '1',
				bpm: 36,
				message: '',
			},
			{
				id: 8,
				level: 'tutorial',
				firstFinger: 1,
				stringNumber: '1',
				bpm: 36,
				message: '',
			},
			{
				id: 9,
				level: 'tutorial',
				firstFinger: 1,
				stringNumber: '1',
				bpm: 38,
				message: '',
			},
			{
				id: 10,
				level: 'tutorial',
				firstFinger: 1,
				stringNumber: '1',
				bpm: 38,
				message: 'Você concluiu o tutorial! Ganhou o 1º troféu!',
			},
			{
				id: 11,
				level: 'beginner',
				firstFinger: 1,
				stringNumber: '1',
				bpm: 40,
				message: '',
			},
			{
				id: 12,
				level: 'beginner',
				firstFinger: 1,
				stringNumber: '1',
				bpm: 42,
				message: '',
			},
			{
				id: 13,
				level: 'beginner',
				firstFinger: 2,
				stringNumber: '1',
				bpm: 42,
				message: '',
			},
			{
				id: 14,
				level: 'beginner',
				firstFinger: 2,
				stringNumber: '1',
				bpm: 44,
				message: '',
			},
			{
				id: 15,
				level: 'beginner',
				firstFinger: 3,
				stringNumber: '1',
				bpm: 44,
				message: '',
			},
			{
				id: 16,
				level: 'beginner',
				firstFinger: 3,
				stringNumber: '1',
				bpm: 46,
				message: '',
			},
			{
				id: 17,
				level: 'beginner',
				firstFinger: 4,
				stringNumber: '1',
				bpm: 46,
				message: '',
			},
			{
				id: 18,
				level: 'beginner',
				firstFinger: 4,
				stringNumber: '1',
				bpm: 48,
				message:
					'Você exercitou todos os dedos. Agora vamos tentar o mesmo com outras cordas! Ganhou o 2º troféu!',
			},
			{
				id: 19,
				level: 'a1',
				firstFinger: 1,
				stringNumber: '2',
				bpm: 40,
				message: '',
			},
			{
				id: 20,
				level: 'a1',
				firstFinger: 1,
				stringNumber: '2',
				bpm: 42,
				message: '',
			},
			{
				id: 21,
				level: 'a1',
				firstFinger: 2,
				stringNumber: '2',
				bpm: 42,
				message: '',
			},
			{
				id: 22,
				level: 'a1',
				firstFinger: 2,
				stringNumber: '2',
				bpm: 44,
				message: '',
			},
			{
				id: 23,
				level: 'a1',
				firstFinger: 3,
				stringNumber: '2',
				bpm: 44,
				message: '',
			},
			{
				id: 24,
				level: 'a1',
				firstFinger: 3,
				stringNumber: '2',
				bpm: 46,
				message: '',
			},
			{
				id: 25,
				level: 'a1',
				firstFinger: 4,
				stringNumber: '2',
				bpm: 46,
				message: '',
			},
			{
				id: 26,
				level: 'a1',
				firstFinger: 4,
				stringNumber: '2',
				bpm: 48,
				message: '',
			},
			{
				id: 27,
				level: 'a1',
				firstFinger: 1,
				stringNumber: '2',
				bpm: 40,
				message: '',
			},
			{
				id: 28,
				level: 'a1',
				firstFinger: 1,
				stringNumber: '2',
				bpm: 42,
				message: '',
			},
			{
				id: 29,
				level: 'a1',
				firstFinger: 2,
				stringNumber: '2',
				bpm: 42,
				message: '',
			},
			{
				id: 30,
				level: 'a1',
				firstFinger: 2,
				stringNumber: '2',
				bpm: 44,
				message: '',
			},
			{
				id: 31,
				level: 'a1',
				firstFinger: 3,
				stringNumber: '2',
				bpm: 44,
				message: 'Você exercitou a segunda corda!',
			},
			{
				id: 32,
				level: 'a1',
				firstFinger: 3,
				stringNumber: '3',
				bpm: 46,
				message: '',
			},
			{
				id: 33,
				level: 'a1',
				firstFinger: 4,
				stringNumber: '3',
				bpm: 46,
				message: '',
			},
			{
				id: 34,
				level: 'a1',
				firstFinger: 4,
				stringNumber: '3',
				bpm: 48,
				message: 'Ganhou o terceiro troféu!',
			},
			{
				id: 35,
				level: 'a2',
				firstFinger: 1,
				stringNumber: '3',
				bpm: 40,
				message: '',
			},
			{
				id: 36,
				level: 'a2',
				firstFinger: 1,
				stringNumber: '3',
				bpm: 42,
				message: '',
			},
			{
				id: 37,
				level: 'a2',
				firstFinger: 2,
				stringNumber: '3',
				bpm: 42,
				message: '',
			},
			{
				id: 38,
				level: 'a2',
				firstFinger: 2,
				stringNumber: '3',
				bpm: 44,
				message: '',
			},
			{
				id: 39,
				level: 'a2',
				firstFinger: 3,
				stringNumber: '3',
				bpm: 44,
				message: '',
			},
			{
				id: 40,
				level: 'a2',
				firstFinger: 3,
				stringNumber: '3',
				bpm: 46,
				message: '',
			},
			{
				id: 41,
				level: 'a2',
				firstFinger: 4,
				stringNumber: '3',
				bpm: 46,
				message: '',
			},
			{
				id: 42,
				level: 'a2',
				firstFinger: 4,
				stringNumber: '3',
				bpm: 48,
				message: '',
			},
			{
				id: 43,
				level: 'a2',
				firstFinger: 1,
				stringNumber: '3',
				bpm: 40,
				message: '',
			},
			{
				id: 44,
				level: 'a2',
				firstFinger: 1,
				stringNumber: '3',
				bpm: 42,
				message: 'Você exercitou a terceira corda!',
			},
			{
				id: 45,
				level: 'a2',
				firstFinger: 2,
				stringNumber: '4',
				bpm: 42,
				message: '',
			},
			{
				id: 46,
				level: 'a2',
				firstFinger: 2,
				stringNumber: '4',
				bpm: 44,
				message: '',
			},
			{
				id: 47,
				level: 'a2',
				firstFinger: 3,
				stringNumber: '4',
				bpm: 44,
				message: '',
			},
			{
				id: 48,
				level: 'a2',
				firstFinger: 3,
				stringNumber: '4',
				bpm: 46,
				message: '',
			},
			{
				id: 49,
				level: 'a2',
				firstFinger: 4,
				stringNumber: '4',
				bpm: 46,
				message: '',
			},
			{
				id: 50,
				level: 'a2',
				firstFinger: 4,
				stringNumber: '4',
				bpm: 48,
				message: '',
			},
			{
				id: 51,
				level: 'a2',
				firstFinger: 1,
				stringNumber: '4',
				bpm: 40,
				message: '',
			},
			{
				id: 52,
				level: 'a2',
				firstFinger: 1,
				stringNumber: '4',
				bpm: 42,
				message: '',
			},
			{
				id: 53,
				level: 'a2',
				firstFinger: 2,
				stringNumber: '4',
				bpm: 42,
				message: '',
			},
			{
				id: 54,
				level: 'a2',
				firstFinger: 2,
				stringNumber: '4',
				bpm: 44,
				message: '',
			},
			{
				id: 55,
				level: 'a2',
				firstFinger: 3,
				stringNumber: '4',
				bpm: 44,
				message: '',
			},
			{
				id: 56,
				level: 'a2',
				firstFinger: 3,
				stringNumber: '4',
				bpm: 46,
				message: '',
			},
			{
				id: 57,
				level: 'a2',
				firstFinger: 4,
				stringNumber: '4',
				bpm: 46,
				message: '',
			},
			{
				id: 58,
				level: 'a2',
				firstFinger: 4,
				stringNumber: '4',
				bpm: 48,
				message:
					'Você exercitou todas as cordas! Que tal dar uma acelerada? Ganhou o quarto troféu!',
			},
			{
				id: 59,
				level: 'b1',
				firstFinger: 1,
				stringNumber: '1',
				bpm: 50,
				message: '',
			},
			{
				id: 60,
				level: 'b1',
				firstFinger: 2,
				stringNumber: '1',
				bpm: 52,
				message: '',
			},
			{
				id: 61,
				level: 'b1',
				firstFinger: 3,
				stringNumber: '1',
				bpm: 54,
				message: '',
			},
			{
				id: 62,
				level: 'b1',
				firstFinger: 4,
				stringNumber: '1',
				bpm: 56,
				message: '',
			},
			{
				id: 63,
				level: 'b1',
				firstFinger: 1,
				stringNumber: '1',
				bpm: 58,
				message: '',
			},
			{
				id: 64,
				level: 'b1',
				firstFinger: 2,
				stringNumber: '1',
				bpm: 60,
				message: '',
			},
			{
				id: 65,
				level: 'b1',
				firstFinger: 3,
				stringNumber: '2',
				bpm: 62,
				message: '',
			},
			{
				id: 66,
				level: 'b1',
				firstFinger: 4,
				stringNumber: '2',
				bpm: 64,
				message: '',
			},
			{
				id: 67,
				level: 'b1',
				firstFinger: 1,
				stringNumber: '2',
				bpm: 66,
				message: '',
			},
			{
				id: 68,
				level: 'b1',
				firstFinger: 2,
				stringNumber: '2',
				bpm: 68,
				message: '',
			},
			{
				id: 69,
				level: 'b1',
				firstFinger: 3,
				stringNumber: '2',
				bpm: 70,
				message: '',
			},
			{
				id: 70,
				level: 'b1',
				firstFinger: 4,
				stringNumber: '2',
				bpm: 72,
				message: '',
			},
			{
				id: 71,
				level: 'b1',
				firstFinger: 1,
				stringNumber: '3',
				bpm: 74,
				message: '',
			},
			{
				id: 72,
				level: 'b1',
				firstFinger: 2,
				stringNumber: '3',
				bpm: 76,
				message: '',
			},
			{
				id: 73,
				level: 'b1',
				firstFinger: 3,
				stringNumber: '3',
				bpm: 78,
				message: '',
			},
			{
				id: 74,
				level: 'b1',
				firstFinger: 4,
				stringNumber: '3',
				bpm: 80,
				message: '',
			},
			{
				id: 75,
				level: 'b1',
				firstFinger: 1,
				stringNumber: '3',
				bpm: 82,
				message: '',
			},
			{
				id: 76,
				level: 'b1',
				firstFinger: 2,
				stringNumber: '3',
				bpm: 84,
				message: '',
			},
			{
				id: 77,
				level: 'b1',
				firstFinger: 3,
				stringNumber: '4',
				bpm: 86,
				message: '',
			},
			{
				id: 78,
				level: 'b1',
				firstFinger: 4,
				stringNumber: '4',
				bpm: 88,
				message: '',
			},
			{
				id: 79,
				level: 'b1',
				firstFinger: 1,
				stringNumber: '4',
				bpm: 90,
				message: '',
			},
			{
				id: 80,
				level: 'b1',
				firstFinger: 2,
				stringNumber: '4',
				bpm: 92,
				message: '',
			},
			{
				id: 81,
				level: 'b1',
				firstFinger: 3,
				stringNumber: '4',
				bpm: 94,
				message: '',
			},
			{
				id: 82,
				level: 'b1',
				firstFinger: 4,
				stringNumber: '4',
				bpm: 96,
				message:
					'Você pegou o jeito! Vamos tentar com várias cordas? Ganhou o quinto troféu',
			},
			{
				id: 83,
				level: 'b2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 60,
				message: '',
			},
			{
				id: 84,
				level: 'b2',
				firstFinger: 2,
				stringNumber: 'downToUp',
				bpm: 60,
				message: '',
			},
			{
				id: 85,
				level: 'b2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 60,
				message: '',
			},
			{
				id: 86,
				level: 'b2',
				firstFinger: 4,
				stringNumber: 'downToUp',
				bpm: 60,
				message: '',
			},
			{
				id: 87,
				level: 'b2',
				firstFinger: 1,
				stringNumber: 'upToDown',
				bpm: 60,
				message: '',
			},
			{
				id: 88,
				level: 'b2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 60,
				message: '',
			},
			{
				id: 89,
				level: 'b2',
				firstFinger: 3,
				stringNumber: 'upToDown',
				bpm: 60,
				message: '',
			},
			{
				id: 90,
				level: 'b2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 60,
				message: '',
			},
			{
				id: 91,
				level: 'b2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 62,
				message: '',
			},
			{
				id: 92,
				level: 'b2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 64,
				message: '',
			},
			{
				id: 93,
				level: 'b2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 66,
				message: '',
			},
			{
				id: 94,
				level: 'b2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 68,
				message: '',
			},
			{
				id: 95,
				level: 'b2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 70,
				message: '',
			},
			{
				id: 96,
				level: 'b2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 72,
				message: '',
			},
			{
				id: 97,
				level: 'b2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 74,
				message: '',
			},
			{
				id: 98,
				level: 'b2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 76,
				message: '',
			},
			{
				id: 99,
				level: 'b2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 78,
				message: '',
			},
			{
				id: 100,
				level: 'b2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 80,
				message: '',
			},
			{
				id: 101,
				level: 'b2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 82,
				message: '',
			},
			{
				id: 102,
				level: 'b2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 84,
				message: '',
			},
			{
				id: 103,
				level: 'b2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 86,
				message: '',
			},
			{
				id: 104,
				level: 'b2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 88,
				message: '',
			},
			{
				id: 105,
				level: 'b2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 90,
				message: '',
			},
			{
				id: 106,
				level: 'b2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 92,
				message: '',
			},
			{
				id: 107,
				level: 'b2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 94,
				message: '',
			},
			{
				id: 108,
				level: 'b2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 96,
				message: '',
			},
			{
				id: 109,
				level: 'b2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 98,
				message: '',
			},
			{
				id: 110,
				level: 'b2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 100,
				message: '',
			},
			{
				id: 111,
				level: 'b2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 102,
				message: '',
			},
			{
				id: 112,
				level: 'b2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 104,
				message: '',
			},
			{
				id: 113,
				level: 'b2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 106,
				message: '',
			},
			{
				id: 114,
				level: 'b2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 108,
				message: '',
			},
			{
				id: 115,
				level: 'b2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 110,
				message: '',
			},
			{
				id: 116,
				level: 'b2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 112,
				message: '',
			},
			{
				id: 117,
				level: 'b2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 114,
				message: '',
			},
			{
				id: 118,
				level: 'b2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 116,
				message: '',
			},
			{
				id: 119,
				level: 'b2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 118,
				message: '',
			},
			{
				id: 120,
				level: 'b2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 120,
				message: 'Você está ficando fera! Ganhou o sexto troféu!',
			},
			{
				id: 121,
				level: 'c1',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 121,
				message: '',
			},
			{
				id: 122,
				level: 'c1',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 122,
				message: '',
			},
			{
				id: 123,
				level: 'c1',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 123,
				message: '',
			},
			{
				id: 124,
				level: 'c1',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 124,
				message: '',
			},
			{
				id: 125,
				level: 'c1',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 125,
				message: '',
			},
			{
				id: 126,
				level: 'c1',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 126,
				message: '',
			},
			{
				id: 127,
				level: 'c1',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 127,
				message: '',
			},
			{
				id: 128,
				level: 'c1',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 128,
				message: '',
			},
			{
				id: 129,
				level: 'c1',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 129,
				message: '',
			},
			{
				id: 130,
				level: 'c1',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 130,
				message: '',
			},
			{
				id: 131,
				level: 'c1',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 131,
				message: '',
			},
			{
				id: 132,
				level: 'c1',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 132,
				message: '',
			},
			{
				id: 133,
				level: 'c1',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 133,
				message: '',
			},
			{
				id: 134,
				level: 'c1',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 134,
				message: '',
			},
			{
				id: 135,
				level: 'c1',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 135,
				message: 'Ganhou o sétimo troféu!',
			},
			{
				id: 136,
				level: 'c2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 136,
				message: '',
			},
			{
				id: 137,
				level: 'c2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 137,
				message: '',
			},
			{
				id: 138,
				level: 'c2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 138,
				message: '',
			},
			{
				id: 139,
				level: 'c2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 139,
				message: '',
			},
			{
				id: 140,
				level: 'c2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 140,
				message: '',
			},
			{
				id: 141,
				level: 'c2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 141,
				message: '',
			},
			{
				id: 142,
				level: 'c2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 142,
				message: '',
			},
			{
				id: 143,
				level: 'c2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 143,
				message: '',
			},
			{
				id: 144,
				level: 'c2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 144,
				message: '',
			},
			{
				id: 145,
				level: 'c2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 145,
				message: '',
			},
			{
				id: 146,
				level: 'c2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 146,
				message: '',
			},
			{
				id: 147,
				level: 'c2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 147,
				message: '',
			},
			{
				id: 148,
				level: 'c2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 148,
				message: '',
			},
			{
				id: 149,
				level: 'c2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 149,
				message: '',
			},
			{
				id: 150,
				level: 'c2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 150,
				message: '',
			},
			{
				id: 151,
				level: 'c2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 151,
				message: '',
			},
			{
				id: 152,
				level: 'c2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 152,
				message: '',
			},
			{
				id: 153,
				level: 'c2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 153,
				message: '',
			},
			{
				id: 154,
				level: 'c2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 154,
				message: '',
			},
			{
				id: 155,
				level: 'c2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 155,
				message: '',
			},
			{
				id: 156,
				level: 'c2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 156,
				message: '',
			},
			{
				id: 157,
				level: 'c2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 157,
				message: '',
			},
			{
				id: 158,
				level: 'c2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 158,
				message: '',
			},
			{
				id: 159,
				level: 'c2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 159,
				message: '',
			},
			{
				id: 160,
				level: 'c2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 160,
				message: '',
			},
			{
				id: 161,
				level: 'c2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 161,
				message: '',
			},
			{
				id: 162,
				level: 'c2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 162,
				message: '',
			},
			{
				id: 163,
				level: 'c2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 163,
				message: '',
			},
			{
				id: 164,
				level: 'c2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 164,
				message: '',
			},
			{
				id: 165,
				level: 'c2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 165,
				message: '',
			},
			{
				id: 166,
				level: 'c2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 166,
				message: '',
			},
			{
				id: 167,
				level: 'c2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 167,
				message: '',
			},
			{
				id: 168,
				level: 'c2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 168,
				message: '',
			},
			{
				id: 169,
				level: 'c2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 169,
				message: '',
			},
			{
				id: 170,
				level: 'c2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 170,
				message: '',
			},
			{
				id: 171,
				level: 'c2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 171,
				message: '',
			},
			{
				id: 172,
				level: 'c2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 172,
				message: '',
			},
			{
				id: 173,
				level: 'c2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 173,
				message: '',
			},
			{
				id: 174,
				level: 'c2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 174,
				message: '',
			},
			{
				id: 175,
				level: 'c2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 175,
				message: '',
			},
			{
				id: 176,
				level: 'c2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 176,
				message: '',
			},
			{
				id: 177,
				level: 'c2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 177,
				message: '',
			},
			{
				id: 178,
				level: 'c2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 178,
				message: '',
			},
			{
				id: 179,
				level: 'c2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 179,
				message: '',
			},
			{
				id: 180,
				level: 'c2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 180,
				message:
					'Você zerou o jogo! Parabéns! Ganhou o mega troféu e seu nome na lista de usuário mestre!',
			},
		] as Lesson[],
		sixStrings: [
			{
				id: 1,
				level: 'tutorial',
				firstFinger: 1,
				stringNumber: '1',
				bpm: 30,
				message: '',
			},
			{
				id: 2,
				level: 'tutorial',
				firstFinger: 1,
				stringNumber: '1',
				bpm: 30,
				message: '',
			},
			{
				id: 3,
				level: 'tutorial',
				firstFinger: 1,
				stringNumber: '1',
				bpm: 32,
				message: '',
			},
			{
				id: 4,
				level: 'tutorial',
				firstFinger: 1,
				stringNumber: '1',
				bpm: 32,
				message: '',
			},
			{
				id: 5,
				level: 'tutorial',
				firstFinger: 1,
				stringNumber: '1',
				bpm: 34,
				message: '',
			},
			{
				id: 6,
				level: 'tutorial',
				firstFinger: 1,
				stringNumber: '1',
				bpm: 34,
				message: '',
			},
			{
				id: 7,
				level: 'tutorial',
				firstFinger: 1,
				stringNumber: '1',
				bpm: 36,
				message: '',
			},
			{
				id: 8,
				level: 'tutorial',
				firstFinger: 1,
				stringNumber: '1',
				bpm: 36,
				message: '',
			},
			{
				id: 9,
				level: 'tutorial',
				firstFinger: 1,
				stringNumber: '1',
				bpm: 38,
				message: '',
			},
			{
				id: 10,
				level: 'tutorial',
				firstFinger: 1,
				stringNumber: '1',
				bpm: 38,
				message: 'Você concluiu o tutorial! Ganhou o 1º troféu!',
			},
			{
				id: 11,
				level: 'beginner',
				firstFinger: 1,
				stringNumber: '1',
				bpm: 40,
				message: '',
			},
			{
				id: 12,
				level: 'beginner',
				firstFinger: 1,
				stringNumber: '1',
				bpm: 42,
				message: '',
			},
			{
				id: 13,
				level: 'beginner',
				firstFinger: 2,
				stringNumber: '1',
				bpm: 42,
				message: '',
			},
			{
				id: 14,
				level: 'beginner',
				firstFinger: 2,
				stringNumber: '1',
				bpm: 44,
				message: '',
			},
			{
				id: 15,
				level: 'beginner',
				firstFinger: 3,
				stringNumber: '1',
				bpm: 44,
				message: '',
			},
			{
				id: 16,
				level: 'beginner',
				firstFinger: 3,
				stringNumber: '1',
				bpm: 46,
				message: '',
			},
			{
				id: 17,
				level: 'beginner',
				firstFinger: 4,
				stringNumber: '1',
				bpm: 46,
				message: '',
			},
			{
				id: 18,
				level: 'beginner',
				firstFinger: 4,
				stringNumber: '1',
				bpm: 48,
				message:
					'Você exercitou todos os dedos. Agora vamos tentar o mesmo com outras cordas! Ganhou o 2º troféu!',
			},
			{
				id: 19,
				level: 'a1',
				firstFinger: 1,
				stringNumber: '2',
				bpm: 40,
				message: '',
			},
			{
				id: 20,
				level: 'a1',
				firstFinger: 1,
				stringNumber: '2',
				bpm: 42,
				message: '',
			},
			{
				id: 21,
				level: 'a1',
				firstFinger: 2,
				stringNumber: '2',
				bpm: 42,
				message: '',
			},
			{
				id: 22,
				level: 'a1',
				firstFinger: 2,
				stringNumber: '2',
				bpm: 44,
				message: '',
			},
			{
				id: 23,
				level: 'a1',
				firstFinger: 3,
				stringNumber: '2',
				bpm: 44,
				message: '',
			},
			{
				id: 24,
				level: 'a1',
				firstFinger: 3,
				stringNumber: '2',
				bpm: 46,
				message: '',
			},
			{
				id: 25,
				level: 'a1',
				firstFinger: 4,
				stringNumber: '2',
				bpm: 46,
				message: '',
			},
			{
				id: 26,
				level: 'a1',
				firstFinger: 4,
				stringNumber: '2',
				bpm: 48,
				message: 'Você exercitou a segunda corda!',
			},
			{
				id: 27,
				level: 'a1',
				firstFinger: 1,
				stringNumber: '3',
				bpm: 40,
				message: '',
			},
			{
				id: 28,
				level: 'a1',
				firstFinger: 1,
				stringNumber: '3',
				bpm: 42,
				message: '',
			},
			{
				id: 29,
				level: 'a1',
				firstFinger: 2,
				stringNumber: '3',
				bpm: 42,
				message: '',
			},
			{
				id: 30,
				level: 'a1',
				firstFinger: 2,
				stringNumber: '3',
				bpm: 44,
				message: '',
			},
			{
				id: 31,
				level: 'a1',
				firstFinger: 3,
				stringNumber: '3',
				bpm: 44,
				message: '',
			},
			{
				id: 32,
				level: 'a1',
				firstFinger: 3,
				stringNumber: '3',
				bpm: 46,
				message: '',
			},
			{
				id: 33,
				level: 'a1',
				firstFinger: 4,
				stringNumber: '3',
				bpm: 46,
				message: '',
			},
			{
				id: 34,
				level: 'a1',
				firstFinger: 4,
				stringNumber: '3',
				bpm: 48,
				message: 'Você exercitou a terceira corda! Ganhou o terceiro troféu!',
			},
			{
				id: 35,
				level: 'a2',
				firstFinger: 1,
				stringNumber: '4',
				bpm: 40,
				message: '',
			},
			{
				id: 36,
				level: 'a2',
				firstFinger: 1,
				stringNumber: '4',
				bpm: 42,
				message: '',
			},
			{
				id: 37,
				level: 'a2',
				firstFinger: 2,
				stringNumber: '4',
				bpm: 42,
				message: '',
			},
			{
				id: 38,
				level: 'a2',
				firstFinger: 2,
				stringNumber: '4',
				bpm: 44,
				message: '',
			},
			{
				id: 39,
				level: 'a2',
				firstFinger: 3,
				stringNumber: '4',
				bpm: 44,
				message: '',
			},
			{
				id: 40,
				level: 'a2',
				firstFinger: 3,
				stringNumber: '4',
				bpm: 46,
				message: '',
			},
			{
				id: 41,
				level: 'a2',
				firstFinger: 4,
				stringNumber: '4',
				bpm: 46,
				message: '',
			},
			{
				id: 42,
				level: 'a2',
				firstFinger: 4,
				stringNumber: '4',
				bpm: 48,
				message: 'Você exercitou a quarta corda!',
			},
			{
				id: 43,
				level: 'a2',
				firstFinger: 1,
				stringNumber: '5',
				bpm: 40,
				message: '',
			},
			{
				id: 44,
				level: 'a2',
				firstFinger: 1,
				stringNumber: '5',
				bpm: 42,
				message: '',
			},
			{
				id: 45,
				level: 'a2',
				firstFinger: 2,
				stringNumber: '5',
				bpm: 42,
				message: '',
			},
			{
				id: 46,
				level: 'a2',
				firstFinger: 2,
				stringNumber: '5',
				bpm: 44,
				message: '',
			},
			{
				id: 47,
				level: 'a2',
				firstFinger: 3,
				stringNumber: '5',
				bpm: 44,
				message: '',
			},
			{
				id: 48,
				level: 'a2',
				firstFinger: 3,
				stringNumber: '5',
				bpm: 46,
				message: '',
			},
			{
				id: 49,
				level: 'a2',
				firstFinger: 4,
				stringNumber: '5',
				bpm: 46,
				message: '',
			},
			{
				id: 50,
				level: 'a2',
				firstFinger: 4,
				stringNumber: '5',
				bpm: 48,
				message: 'Você exercitou a quinta corda!',
			},
			{
				id: 51,
				level: 'a2',
				firstFinger: 1,
				stringNumber: '6',
				bpm: 40,
				message: '',
			},
			{
				id: 52,
				level: 'a2',
				firstFinger: 1,
				stringNumber: '6',
				bpm: 42,
				message: '',
			},
			{
				id: 53,
				level: 'a2',
				firstFinger: 2,
				stringNumber: '6',
				bpm: 42,
				message: '',
			},
			{
				id: 54,
				level: 'a2',
				firstFinger: 2,
				stringNumber: '6',
				bpm: 44,
				message: '',
			},
			{
				id: 55,
				level: 'a2',
				firstFinger: 3,
				stringNumber: '6',
				bpm: 44,
				message: '',
			},
			{
				id: 56,
				level: 'a2',
				firstFinger: 3,
				stringNumber: '6',
				bpm: 46,
				message: '',
			},
			{
				id: 57,
				level: 'a2',
				firstFinger: 4,
				stringNumber: '6',
				bpm: 46,
				message: '',
			},
			{
				id: 58,
				level: 'a2',
				firstFinger: 4,
				stringNumber: '6',
				bpm: 48,
				message:
					'Você exercitou todas as cordas! Que tal dar uma acelerada? Ganhou o quarto troféu!',
			},
			{
				id: 59,
				level: 'b1',
				firstFinger: 1,
				stringNumber: '1',
				bpm: 50,
				message: '',
			},
			{
				id: 60,
				level: 'b1',
				firstFinger: 2,
				stringNumber: '1',
				bpm: 52,
				message: '',
			},
			{
				id: 61,
				level: 'b1',
				firstFinger: 3,
				stringNumber: '1',
				bpm: 54,
				message: '',
			},
			{
				id: 62,
				level: 'b1',
				firstFinger: 4,
				stringNumber: '1',
				bpm: 56,
				message: '',
			},
			{
				id: 63,
				level: 'b1',
				firstFinger: 1,
				stringNumber: '2',
				bpm: 58,
				message: '',
			},
			{
				id: 64,
				level: 'b1',
				firstFinger: 2,
				stringNumber: '2',
				bpm: 60,
				message: '',
			},
			{
				id: 65,
				level: 'b1',
				firstFinger: 3,
				stringNumber: '2',
				bpm: 62,
				message: '',
			},
			{
				id: 66,
				level: 'b1',
				firstFinger: 4,
				stringNumber: '2',
				bpm: 64,
				message: '',
			},
			{
				id: 67,
				level: 'b1',
				firstFinger: 1,
				stringNumber: '3',
				bpm: 66,
				message: '',
			},
			{
				id: 68,
				level: 'b1',
				firstFinger: 2,
				stringNumber: '3',
				bpm: 68,
				message: '',
			},
			{
				id: 69,
				level: 'b1',
				firstFinger: 3,
				stringNumber: '3',
				bpm: 70,
				message: '',
			},
			{
				id: 70,
				level: 'b1',
				firstFinger: 4,
				stringNumber: '3',
				bpm: 72,
				message: '',
			},
			{
				id: 71,
				level: 'b1',
				firstFinger: 1,
				stringNumber: '4',
				bpm: 74,
				message: '',
			},
			{
				id: 72,
				level: 'b1',
				firstFinger: 2,
				stringNumber: '4',
				bpm: 76,
				message: '',
			},
			{
				id: 73,
				level: 'b1',
				firstFinger: 3,
				stringNumber: '4',
				bpm: 78,
				message: '',
			},
			{
				id: 74,
				level: 'b1',
				firstFinger: 4,
				stringNumber: '4',
				bpm: 80,
				message: '',
			},
			{
				id: 75,
				level: 'b1',
				firstFinger: 1,
				stringNumber: '5',
				bpm: 82,
				message: '',
			},
			{
				id: 76,
				level: 'b1',
				firstFinger: 2,
				stringNumber: '5',
				bpm: 84,
				message: '',
			},
			{
				id: 77,
				level: 'b1',
				firstFinger: 3,
				stringNumber: '5',
				bpm: 86,
				message: '',
			},
			{
				id: 78,
				level: 'b1',
				firstFinger: 4,
				stringNumber: '5',
				bpm: 88,
				message: '',
			},
			{
				id: 79,
				level: 'b1',
				firstFinger: 1,
				stringNumber: '6',
				bpm: 90,
				message: '',
			},
			{
				id: 80,
				level: 'b1',
				firstFinger: 2,
				stringNumber: '6',
				bpm: 92,
				message: '',
			},
			{
				id: 81,
				level: 'b1',
				firstFinger: 3,
				stringNumber: '6',
				bpm: 94,
				message: '',
			},
			{
				id: 82,
				level: 'b1',
				firstFinger: 4,
				stringNumber: '6',
				bpm: 96,
				message:
					'Você pegou o jeito! Vamos tentar com várias cordas? Ganhou o quinto troféu',
			},
			{
				id: 83,
				level: 'b2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 60,
				message: '',
			},
			{
				id: 84,
				level: 'b2',
				firstFinger: 2,
				stringNumber: 'downToUp',
				bpm: 60,
				message: '',
			},
			{
				id: 85,
				level: 'b2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 60,
				message: '',
			},
			{
				id: 86,
				level: 'b2',
				firstFinger: 4,
				stringNumber: 'downToUp',
				bpm: 60,
				message: '',
			},
			{
				id: 87,
				level: 'b2',
				firstFinger: 1,
				stringNumber: 'upToDown',
				bpm: 60,
				message: '',
			},
			{
				id: 88,
				level: 'b2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 60,
				message: '',
			},
			{
				id: 89,
				level: 'b2',
				firstFinger: 3,
				stringNumber: 'upToDown',
				bpm: 60,
				message: '',
			},
			{
				id: 90,
				level: 'b2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 60,
				message: '',
			},
			{
				id: 91,
				level: 'b2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 62,
				message: '',
			},
			{
				id: 92,
				level: 'b2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 64,
				message: '',
			},
			{
				id: 93,
				level: 'b2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 66,
				message: '',
			},
			{
				id: 94,
				level: 'b2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 68,
				message: '',
			},
			{
				id: 95,
				level: 'b2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 70,
				message: '',
			},
			{
				id: 96,
				level: 'b2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 72,
				message: '',
			},
			{
				id: 97,
				level: 'b2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 74,
				message: '',
			},
			{
				id: 98,
				level: 'b2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 76,
				message: '',
			},
			{
				id: 99,
				level: 'b2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 78,
				message: '',
			},
			{
				id: 100,
				level: 'b2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 80,
				message: '',
			},
			{
				id: 101,
				level: 'b2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 82,
				message: '',
			},
			{
				id: 102,
				level: 'b2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 84,
				message: '',
			},
			{
				id: 103,
				level: 'b2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 86,
				message: '',
			},
			{
				id: 104,
				level: 'b2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 88,
				message: '',
			},
			{
				id: 105,
				level: 'b2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 90,
				message: '',
			},
			{
				id: 106,
				level: 'b2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 92,
				message: '',
			},
			{
				id: 107,
				level: 'b2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 94,
				message: '',
			},
			{
				id: 108,
				level: 'b2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 96,
				message: '',
			},
			{
				id: 109,
				level: 'b2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 98,
				message: '',
			},
			{
				id: 110,
				level: 'b2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 100,
				message: '',
			},
			{
				id: 111,
				level: 'b2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 102,
				message: '',
			},
			{
				id: 112,
				level: 'b2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 104,
				message: '',
			},
			{
				id: 113,
				level: 'b2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 106,
				message: '',
			},
			{
				id: 114,
				level: 'b2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 108,
				message: '',
			},
			{
				id: 115,
				level: 'b2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 110,
				message: '',
			},
			{
				id: 116,
				level: 'b2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 112,
				message: '',
			},
			{
				id: 117,
				level: 'b2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 114,
				message: '',
			},
			{
				id: 118,
				level: 'b2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 116,
				message: '',
			},
			{
				id: 119,
				level: 'b2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 118,
				message: '',
			},
			{
				id: 120,
				level: 'b2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 120,
				message: 'Você está ficando fera! Ganhou o sexto troféu!',
			},
			{
				id: 121,
				level: 'c1',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 121,
				message: '',
			},
			{
				id: 122,
				level: 'c1',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 122,
				message: '',
			},
			{
				id: 123,
				level: 'c1',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 123,
				message: '',
			},
			{
				id: 124,
				level: 'c1',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 124,
				message: '',
			},
			{
				id: 125,
				level: 'c1',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 125,
				message: '',
			},
			{
				id: 126,
				level: 'c1',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 126,
				message: '',
			},
			{
				id: 127,
				level: 'c1',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 127,
				message: '',
			},
			{
				id: 128,
				level: 'c1',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 128,
				message: '',
			},
			{
				id: 129,
				level: 'c1',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 129,
				message: '',
			},
			{
				id: 130,
				level: 'c1',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 130,
				message: '',
			},
			{
				id: 131,
				level: 'c1',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 131,
				message: '',
			},
			{
				id: 132,
				level: 'c1',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 132,
				message: '',
			},
			{
				id: 133,
				level: 'c1',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 133,
				message: '',
			},
			{
				id: 134,
				level: 'c1',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 134,
				message: '',
			},
			{
				id: 135,
				level: 'c1',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 135,
				message: 'Ganhou o sétimo troféu!',
			},
			{
				id: 136,
				level: 'c2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 136,
				message: '',
			},
			{
				id: 137,
				level: 'c2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 137,
				message: '',
			},
			{
				id: 138,
				level: 'c2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 138,
				message: '',
			},
			{
				id: 139,
				level: 'c2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 139,
				message: '',
			},
			{
				id: 140,
				level: 'c2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 140,
				message: '',
			},
			{
				id: 141,
				level: 'c2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 141,
				message: '',
			},
			{
				id: 142,
				level: 'c2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 142,
				message: '',
			},
			{
				id: 143,
				level: 'c2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 143,
				message: '',
			},
			{
				id: 144,
				level: 'c2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 144,
				message: '',
			},
			{
				id: 145,
				level: 'c2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 145,
				message: '',
			},
			{
				id: 146,
				level: 'c2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 146,
				message: '',
			},
			{
				id: 147,
				level: 'c2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 147,
				message: '',
			},
			{
				id: 148,
				level: 'c2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 148,
				message: '',
			},
			{
				id: 149,
				level: 'c2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 149,
				message: '',
			},
			{
				id: 150,
				level: 'c2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 150,
				message: '',
			},
			{
				id: 151,
				level: 'c2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 151,
				message: '',
			},
			{
				id: 152,
				level: 'c2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 152,
				message: '',
			},
			{
				id: 153,
				level: 'c2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 153,
				message: '',
			},
			{
				id: 154,
				level: 'c2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 154,
				message: '',
			},
			{
				id: 155,
				level: 'c2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 155,
				message: '',
			},
			{
				id: 156,
				level: 'c2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 156,
				message: '',
			},
			{
				id: 157,
				level: 'c2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 157,
				message: '',
			},
			{
				id: 158,
				level: 'c2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 158,
				message: '',
			},
			{
				id: 159,
				level: 'c2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 159,
				message: '',
			},
			{
				id: 160,
				level: 'c2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 160,
				message: '',
			},
			{
				id: 161,
				level: 'c2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 161,
				message: '',
			},
			{
				id: 162,
				level: 'c2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 162,
				message: '',
			},
			{
				id: 163,
				level: 'c2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 163,
				message: '',
			},
			{
				id: 164,
				level: 'c2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 164,
				message: '',
			},
			{
				id: 165,
				level: 'c2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 165,
				message: '',
			},
			{
				id: 166,
				level: 'c2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 166,
				message: '',
			},
			{
				id: 167,
				level: 'c2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 167,
				message: '',
			},
			{
				id: 168,
				level: 'c2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 168,
				message: '',
			},
			{
				id: 169,
				level: 'c2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 169,
				message: '',
			},
			{
				id: 170,
				level: 'c2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 170,
				message: '',
			},
			{
				id: 171,
				level: 'c2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 171,
				message: '',
			},
			{
				id: 172,
				level: 'c2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 172,
				message: '',
			},
			{
				id: 173,
				level: 'c2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 173,
				message: '',
			},
			{
				id: 174,
				level: 'c2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 174,
				message: '',
			},
			{
				id: 175,
				level: 'c2',
				firstFinger: 1,
				stringNumber: 'downToUp',
				bpm: 175,
				message: '',
			},
			{
				id: 176,
				level: 'c2',
				firstFinger: 2,
				stringNumber: 'upToDown',
				bpm: 176,
				message: '',
			},
			{
				id: 177,
				level: 'c2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 177,
				message: '',
			},
			{
				id: 178,
				level: 'c2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 178,
				message: '',
			},
			{
				id: 179,
				level: 'c2',
				firstFinger: 3,
				stringNumber: 'downToUp',
				bpm: 179,
				message: '',
			},
			{
				id: 180,
				level: 'c2',
				firstFinger: 4,
				stringNumber: 'upToDown',
				bpm: 180,
				message:
					'Você zerou o jogo! Parabéns! Ganhou o mega troféu e seu nome no hall de usuário mestre!',
			},
		] as Lesson[],
	}

	function getLessons(instrument: string) {
		switch (true) {
			case instrument === 'bass' || instrument === 'cavaco':
				return lessons.fourStrings
			case instrument === 'acoustic-guitar' || instrument === 'eletric-guitar':
				return lessons.sixStrings
			default:
				return [getEmptyLesson()]
		}
	}

	function getLesson(id: number, instrument: string) {
		switch (true) {
			case instrument === 'bass' || instrument === 'cavaco':
				return lessons.fourStrings.find((lesson) => lesson.id === id)
			case instrument === 'acoustic-guitar' || instrument === 'eletric-guitar':
				return lessons.sixStrings.find((lesson) => lesson.id === id)
				break
			default:
				break
		}
		return getEmptyLesson()
	}

	function getEmptyLesson() {
		return {
			id: 0,
			level: '',
			firstFinger: 0,
			stringNumber: '',
			bpm: 0,
			message: '',
		}
	}

	return {
		getLessons,
		getLesson,
		getEmptyLesson,
	}
}
