import type { Lesson } from '~/types/Lesson'

const lessons = [
	{
		number: 1,
		level: 'tutorial',
		firstFinger: 0,
		stringNumber: '1',
		bpm: 30,
		message: '',
		quantityOfStrings: 6,
		points: 5,
	},
	{
		number: 2,
		level: 'tutorial',
		firstFinger: 0,
		stringNumber: '1',
		bpm: 30,
		message: '',
		quantityOfStrings: 6,
		points: 5,
	},
	{
		number: 3,
		level: 'tutorial',
		firstFinger: 0,
		stringNumber: '1',
		bpm: 32,
		message: '',
		quantityOfStrings: 6,
		points: 5,
	},
	{
		number: 4,
		level: 'tutorial',
		firstFinger: 0,
		stringNumber: '1',
		bpm: 32,
		message: '',
		quantityOfStrings: 6,
		points: 5,
	},
	{
		number: 5,
		level: 'tutorial',
		firstFinger: 0,
		stringNumber: '1',
		bpm: 34,
		message: '',
		quantityOfStrings: 6,
		points: 5,
	},
	{
		number: 6,
		level: 'tutorial',
		firstFinger: 0,
		stringNumber: '1',
		bpm: 34,
		message: '',
		quantityOfStrings: 6,
		points: 5,
	},
	{
		number: 7,
		level: 'tutorial',
		firstFinger: 0,
		stringNumber: '1',
		bpm: 36,
		message: '',
		quantityOfStrings: 6,
		points: 5,
	},
	{
		number: 8,
		level: 'tutorial',
		firstFinger: 0,
		stringNumber: '1',
		bpm: 36,
		message: '',
		quantityOfStrings: 6,
		points: 5,
	},
	{
		number: 9,
		level: 'tutorial',
		firstFinger: 0,
		stringNumber: '1',
		bpm: 38,
		message: '',
		quantityOfStrings: 6,
		points: 5,
	},
	{
		number: 10,
		level: 'tutorial',
		firstFinger: 0,
		stringNumber: '1',
		bpm: 38,
		quantityOfStrings: 6,
		message: 'Você concluiu o tutorial! Ganhou o 1º troféu!',
		points: 10,
	},
	{
		number: 11,
		level: 'Iniciante',
		firstFinger: 0,
		stringNumber: '1',
		bpm: 40,
		message: '',
		quantityOfStrings: 6,
		points: 15,
	},
	{
		number: 12,
		level: 'Iniciante',
		firstFinger: 0,
		stringNumber: '1',
		bpm: 42,
		message: '',
		quantityOfStrings: 6,
		points: 15,
	},
	{
		number: 13,
		level: 'Iniciante',
		firstFinger: 1,
		stringNumber: '1',
		bpm: 40,
		message: '',
		quantityOfStrings: 6,
		points: 15,
	},
	{
		number: 14,
		level: 'Iniciante',
		firstFinger: 1,
		stringNumber: '1',
		bpm: 42,
		message: '',
		quantityOfStrings: 6,
		points: 15,
	},
	{
		number: 15,
		level: 'Iniciante',
		firstFinger: 2,
		stringNumber: '1',
		bpm: 42,
		message: '',
		quantityOfStrings: 6,
		points: 15,
	},
	{
		number: 16,
		level: 'Iniciante',
		firstFinger: 2,
		stringNumber: '1',
		bpm: 44,
		message: '',
		quantityOfStrings: 6,
		points: 15,
	},
	{
		number: 17,
		level: 'Iniciante',
		firstFinger: 3,
		stringNumber: '1',
		bpm: 44,
		message: '',
		quantityOfStrings: 6,
		points: 15,
	},
	{
		number: 18,
		level: 'Iniciante',
		firstFinger: 3,
		stringNumber: '1',
		bpm: 46,
		message: '',
		quantityOfStrings: 6,
		points: 15,
	},
	{
		number: 19,
		level: 'Iniciante',
		firstFinger: 4,
		stringNumber: '1',
		bpm: 46,
		message: '',
		quantityOfStrings: 6,
		points: 15,
	},
	{
		number: 20,
		level: 'Iniciante',
		firstFinger: 4,
		stringNumber: '1',
		bpm: 48,
		message:
			'Você exercitou todos os dedos. Agora vamos tentar o mesmo com outras cordas! Ganhou o 2º troféu!',
		quantityOfStrings: 6,
		points: 30,
	},
	{
		number: 21,
		level: 'Básico I',
		firstFinger: 0,
		stringNumber: '2',
		bpm: 40,
		message: '',
		quantityOfStrings: 6,
		points: 30,
	},
	{
		number: 22,
		level: 'Básico I',
		firstFinger: 0,
		stringNumber: '2',
		bpm: 42,
		message: '',
		quantityOfStrings: 6,
		points: 30,
	},
	{
		number: 23,
		level: 'Básico I',
		firstFinger: 1,
		stringNumber: '2',
		bpm: 40,
		message: '',
		quantityOfStrings: 6,
		points: 30,
	},
	{
		number: 24,
		level: 'Básico I',
		firstFinger: 1,
		stringNumber: '2',
		bpm: 42,
		message: '',
		quantityOfStrings: 6,
		points: 30,
	},
	{
		number: 25,
		level: 'Básico I',
		firstFinger: 2,
		stringNumber: '2',
		bpm: 42,
		message: '',
		quantityOfStrings: 6,
		points: 30,
	},
	{
		number: 26,
		level: 'Básico I',
		firstFinger: 2,
		stringNumber: '2',
		bpm: 44,
		message: '',
		quantityOfStrings: 6,
		points: 30,
	},
	{
		number: 27,
		level: 'Básico I',
		firstFinger: 3,
		stringNumber: '2',
		bpm: 44,
		message: '',
		quantityOfStrings: 6,
		points: 30,
	},
	{
		number: 28,
		level: 'Básico I',
		firstFinger: 3,
		stringNumber: '2',
		bpm: 46,
		message: '',
		quantityOfStrings: 6,
		points: 30,
	},
	{
		number: 29,
		level: 'Básico I',
		firstFinger: 4,
		stringNumber: '2',
		bpm: 46,
		message: '',
		quantityOfStrings: 6,
		points: 30,
	},
	{
		number: 30,
		level: 'Básico I',
		firstFinger: 4,
		stringNumber: '2',
		bpm: 48,
		message: 'Você exercitou a segunda corda!',
		quantityOfStrings: 6,
		points: 30,
	},
	{
		number: 31,
		level: 'Básico I',
		firstFinger: 0,
		stringNumber: '3',
		bpm: 40,
		message: '',
		quantityOfStrings: 6,
		points: 30,
	},
	{
		number: 32,
		level: 'Básico I',
		firstFinger: 0,
		stringNumber: '3',
		bpm: 42,
		message: '',
		quantityOfStrings: 6,
		points: 30,
	},
	{
		number: 33,
		level: 'Básico I',
		firstFinger: 1,
		stringNumber: '3',
		bpm: 40,
		message: '',
		quantityOfStrings: 6,
		points: 30,
	},
	{
		number: 34,
		level: 'Básico I',
		firstFinger: 1,
		stringNumber: '3',
		bpm: 42,
		message: '',
		quantityOfStrings: 6,
		points: 30,
	},
	{
		number: 35,
		level: 'Básico I',
		firstFinger: 2,
		stringNumber: '3',
		bpm: 42,
		message: '',
		quantityOfStrings: 6,
		points: 30,
	},
	{
		number: 36,
		level: 'Básico I',
		firstFinger: 2,
		stringNumber: '3',
		bpm: 44,
		message: '',
		quantityOfStrings: 6,
		points: 30,
	},
	{
		number: 37,
		level: 'Básico I',
		firstFinger: 3,
		stringNumber: '3',
		bpm: 44,
		message: '',
		quantityOfStrings: 6,
		points: 30,
	},
	{
		number: 38,
		level: 'Básico I',
		firstFinger: 3,
		stringNumber: '3',
		bpm: 46,
		message: '',
		quantityOfStrings: 6,
		points: 30,
	},
	{
		number: 39,
		level: 'Básico I',
		firstFinger: 4,
		stringNumber: '3',
		bpm: 46,
		message: '',
		quantityOfStrings: 6,
		points: 30,
	},
	{
		number: 40,
		level: 'Básico I',
		firstFinger: 4,
		stringNumber: '3',
		bpm: 48,
		message: 'Você exercitou a terceira corda! Ganhou o terceiro troféu!',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 41,
		level: 'Básico II',
		firstFinger: 0,
		stringNumber: '4',
		bpm: 40,
		message: '',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 42,
		level: 'Básico II',
		firstFinger: 0,
		stringNumber: '4',
		bpm: 42,
		message: '',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 43,
		level: 'Básico II',
		firstFinger: 1,
		stringNumber: '4',
		bpm: 40,
		message: '',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 44,
		level: 'Básico II',
		firstFinger: 1,
		stringNumber: '4',
		bpm: 42,
		message: '',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 45,
		level: 'Básico II',
		firstFinger: 2,
		stringNumber: '4',
		bpm: 42,
		message: '',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 46,
		level: 'Básico II',
		firstFinger: 2,
		stringNumber: '4',
		bpm: 44,
		message: '',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 47,
		level: 'Básico II',
		firstFinger: 3,
		stringNumber: '4',
		bpm: 44,
		message: '',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 48,
		level: 'Básico II',
		firstFinger: 3,
		stringNumber: '4',
		bpm: 46,
		message: '',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 49,
		level: 'Básico II',
		firstFinger: 4,
		stringNumber: '4',
		bpm: 46,
		message: '',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 50,
		level: 'Básico II',
		firstFinger: 4,
		stringNumber: '4',
		bpm: 48,
		message: 'Você exercitou a quarta corda!',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 51,
		level: 'Básico II',
		firstFinger: 0,
		stringNumber: '5',
		bpm: 40,
		message: '',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 52,
		level: 'Básico II',
		firstFinger: 0,
		stringNumber: '5',
		bpm: 42,
		message: '',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 53,
		level: 'Básico II',
		firstFinger: 1,
		stringNumber: '5',
		bpm: 40,
		message: '',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 54,
		level: 'Básico II',
		firstFinger: 1,
		stringNumber: '5',
		bpm: 42,
		message: '',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 55,
		level: 'Básico II',
		firstFinger: 2,
		stringNumber: '5',
		bpm: 42,
		message: '',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 56,
		level: 'Básico II',
		firstFinger: 2,
		stringNumber: '5',
		bpm: 44,
		message: '',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 57,
		level: 'Básico II',
		firstFinger: 3,
		stringNumber: '5',
		bpm: 44,
		message: '',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 58,
		level: 'Básico II',
		firstFinger: 3,
		stringNumber: '5',
		bpm: 46,
		message: '',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 59,
		level: 'Básico II',
		firstFinger: 4,
		stringNumber: '5',
		bpm: 46,
		message: '',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 60,
		level: 'Básico II',
		firstFinger: 4,
		stringNumber: '5',
		bpm: 48,
		message: 'Você exercitou a quinta corda!',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 61,
		level: 'Básico II',
		firstFinger: 0,
		stringNumber: '6',
		bpm: 40,
		message: '',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 62,
		level: 'Básico II',
		firstFinger: 0,
		stringNumber: '6',
		bpm: 42,
		message: '',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 63,
		level: 'Básico II',
		firstFinger: 1,
		stringNumber: '6',
		bpm: 40,
		message: '',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 64,
		level: 'Básico II',
		firstFinger: 1,
		stringNumber: '6',
		bpm: 42,
		message: '',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 65,
		level: 'Básico II',
		firstFinger: 2,
		stringNumber: '6',
		bpm: 42,
		message: '',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 66,
		level: 'Básico II',
		firstFinger: 2,
		stringNumber: '6',
		bpm: 44,
		message: '',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 67,
		level: 'Básico II',
		firstFinger: 3,
		stringNumber: '6',
		bpm: 44,
		message: '',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 68,
		level: 'Básico II',
		firstFinger: 3,
		stringNumber: '6',
		bpm: 46,
		message: '',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 69,
		level: 'Básico II',
		firstFinger: 4,
		stringNumber: '6',
		bpm: 46,
		message: '',
		quantityOfStrings: 6,
		points: 40,
	},
	{
		number: 70,
		level: 'Básico II',
		firstFinger: 4,
		stringNumber: '6',
		bpm: 48,
		message:
			'Você exercitou todas as cordas! Que tal dar uma acelerada? Ganhou o quarto troféu!',
		quantityOfStrings: 6,
		points: 80,
	},
	{
		number: 71,
		level: 'Intermediário I',
		firstFinger: 0,
		stringNumber: '1',
		bpm: 50,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 72,
		level: 'Intermediário I',
		firstFinger: 1,
		stringNumber: '1',
		bpm: 50,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 73,
		level: 'Intermediário I',
		firstFinger: 2,
		stringNumber: '1',
		bpm: 52,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 74,
		level: 'Intermediário I',
		firstFinger: 3,
		stringNumber: '1',
		bpm: 54,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 75,
		level: 'Intermediário I',
		firstFinger: 4,
		stringNumber: '1',
		bpm: 56,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 76,
		level: 'Intermediário I',
		firstFinger: 0,
		stringNumber: '2',
		bpm: 58,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 77,
		level: 'Intermediário I',
		firstFinger: 1,
		stringNumber: '2',
		bpm: 58,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 78,
		level: 'Intermediário I',
		firstFinger: 2,
		stringNumber: '2',
		bpm: 60,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 79,
		level: 'Intermediário I',
		firstFinger: 3,
		stringNumber: '2',
		bpm: 62,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 80,
		level: 'Intermediário I',
		firstFinger: 4,
		stringNumber: '2',
		bpm: 64,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 81,
		level: 'Intermediário I',
		firstFinger: 0,
		stringNumber: '3',
		bpm: 66,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 82,
		level: 'Intermediário I',
		firstFinger: 1,
		stringNumber: '3',
		bpm: 66,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 83,
		level: 'Intermediário I',
		firstFinger: 2,
		stringNumber: '3',
		bpm: 68,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 84,
		level: 'Intermediário I',
		firstFinger: 3,
		stringNumber: '3',
		bpm: 70,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 85,
		level: 'Intermediário I',
		firstFinger: 4,
		stringNumber: '3',
		bpm: 72,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 86,
		level: 'Intermediário I',
		firstFinger: 0,
		stringNumber: '4',
		bpm: 74,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 87,
		level: 'Intermediário I',
		firstFinger: 1,
		stringNumber: '4',
		bpm: 74,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 88,
		level: 'Intermediário I',
		firstFinger: 2,
		stringNumber: '4',
		bpm: 76,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 89,
		level: 'Intermediário I',
		firstFinger: 3,
		stringNumber: '4',
		bpm: 78,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 90,
		level: 'Intermediário I',
		firstFinger: 4,
		stringNumber: '4',
		bpm: 80,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 91,
		level: 'Intermediário I',
		firstFinger: 0,
		stringNumber: '5',
		bpm: 82,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 92,
		level: 'Intermediário I',
		firstFinger: 1,
		stringNumber: '5',
		bpm: 82,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 93,
		level: 'Intermediário I',
		firstFinger: 2,
		stringNumber: '5',
		bpm: 84,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 94,
		level: 'Intermediário I',
		firstFinger: 3,
		stringNumber: '5',
		bpm: 88,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 95,
		level: 'Intermediário I',
		firstFinger: 4,
		stringNumber: '5',
		bpm: 90,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 96,
		level: 'Intermediário I',
		firstFinger: 0,
		stringNumber: '6',
		bpm: 92,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 97,
		level: 'Intermediário I',
		firstFinger: 1,
		stringNumber: '6',
		bpm: 94,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 98,
		level: 'Intermediário I',
		firstFinger: 2,
		stringNumber: '6',
		bpm: 96,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 99,
		level: 'Intermediário I',
		firstFinger: 3,
		stringNumber: '6',
		bpm: 98,
		message: '',
		quantityOfStrings: 6,
		points: 50,
	},
	{
		number: 100,
		level: 'Intermediário I',
		firstFinger: 4,
		stringNumber: '6',
		bpm: 100,
		message:
			'Você pegou o jeito! Vamos tentar com várias cordas? Ganhou o quinto troféu',
		quantityOfStrings: 6,
		points: 100,
	},
	{
		number: 101,
		level: 'Intermediário II',
		firstFinger: 0,
		stringNumber: 'downToUp',
		bpm: 60,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 102,
		level: 'Intermediário II',
		firstFinger: 0,
		stringNumber: 'downToUp',
		bpm: 60,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 103,
		level: 'Intermediário II',
		firstFinger: 1,
		stringNumber: 'downToUp',
		bpm: 60,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 104,
		level: 'Intermediário II',
		firstFinger: 1,
		stringNumber: 'downToUp',
		bpm: 60,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 105,
		level: 'Intermediário II',
		firstFinger: 2,
		stringNumber: 'downToUp',
		bpm: 60,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 106,
		level: 'Intermediário II',
		firstFinger: 2,
		stringNumber: 'downToUp',
		bpm: 60,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 107,
		level: 'Intermediário II',
		firstFinger: 3,
		stringNumber: 'downToUp',
		bpm: 60,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 108,
		level: 'Intermediário II',
		firstFinger: 3,
		stringNumber: 'downToUp',
		bpm: 60,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 109,
		level: 'Intermediário II',
		firstFinger: 4,
		stringNumber: 'downToUp',
		bpm: 60,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 110,
		level: 'Intermediário II',
		firstFinger: 4,
		stringNumber: 'downToUp',
		bpm: 60,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 111,
		level: 'Intermediário II',
		firstFinger: 0,
		stringNumber: 'upToDown',
		bpm: 60,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 112,
		level: 'Intermediário II',
		firstFinger: 0,
		stringNumber: 'upToDown',
		bpm: 60,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 113,
		level: 'Intermediário II',
		firstFinger: 1,
		stringNumber: 'upToDown',
		bpm: 60,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 114,
		level: 'Intermediário II',
		firstFinger: 1,
		stringNumber: 'upToDown',
		bpm: 60,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 115,
		level: 'Intermediário II',
		firstFinger: 2,
		stringNumber: 'upToDown',
		bpm: 60,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 116,
		level: 'Intermediário II',
		firstFinger: 2,
		stringNumber: 'upToDown',
		bpm: 60,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 117,
		level: 'Intermediário II',
		firstFinger: 3,
		stringNumber: 'upToDown',
		bpm: 60,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 118,
		level: 'Intermediário II',
		firstFinger: 3,
		stringNumber: 'upToDown',
		bpm: 60,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 119,
		level: 'Intermediário II',
		firstFinger: 4,
		stringNumber: 'upToDown',
		bpm: 60,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 120,
		level: 'Intermediário II',
		firstFinger: 4,
		stringNumber: 'upToDown',
		bpm: 60,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 121,
		level: 'Intermediário II',
		firstFinger: 0,
		stringNumber: 'downToUp',
		bpm: 62,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 122,
		level: 'Intermediário II',
		firstFinger: 1,
		stringNumber: 'upToDown',
		bpm: 64,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 123,
		level: 'Intermediário II',
		firstFinger: 2,
		stringNumber: 'downToUp',
		bpm: 66,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 124,
		level: 'Intermediário II',
		firstFinger: 3,
		stringNumber: 'upToDown',
		bpm: 68,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 125,
		level: 'Intermediário II',
		firstFinger: 4,
		stringNumber: 'downToUp',
		bpm: 70,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 126,
		level: 'Intermediário II',
		firstFinger: 0,
		stringNumber: 'upToDown',
		bpm: 72,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 127,
		level: 'Intermediário II',
		firstFinger: 1,
		stringNumber: 'downToUp',
		bpm: 74,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 128,
		level: 'Intermediário II',
		firstFinger: 2,
		stringNumber: 'upToDown',
		bpm: 76,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 129,
		level: 'Intermediário II',
		firstFinger: 3,
		stringNumber: 'downToUp',
		bpm: 78,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 130,
		level: 'Intermediário II',
		firstFinger: 4,
		stringNumber: 'upToDown',
		bpm: 80,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 131,
		level: 'Intermediário II',
		firstFinger: 0,
		stringNumber: 'downToUp',
		bpm: 82,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 132,
		level: 'Intermediário II',
		firstFinger: 1,
		stringNumber: 'upToDown',
		bpm: 84,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 133,
		level: 'Intermediário II',
		firstFinger: 2,
		stringNumber: 'downToUp',
		bpm: 86,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 134,
		level: 'Intermediário II',
		firstFinger: 3,
		stringNumber: 'upToDown',
		bpm: 88,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 135,
		level: 'Intermediário II',
		firstFinger: 4,
		stringNumber: 'downToUp',
		bpm: 90,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 136,
		level: 'Intermediário II',
		firstFinger: 0,
		stringNumber: 'upToDown',
		bpm: 92,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 137,
		level: 'Intermediário II',
		firstFinger: 1,
		stringNumber: 'downToUp',
		bpm: 94,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 138,
		level: 'Intermediário II',
		firstFinger: 2,
		stringNumber: 'upToDown',
		bpm: 96,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 139,
		level: 'Intermediário II',
		firstFinger: 3,
		stringNumber: 'downToUp',
		bpm: 98,
		message: '',
		quantityOfStrings: 6,
		points: 60,
	},
	{
		number: 140,
		level: 'Intermediário II',
		firstFinger: 4,
		stringNumber: 'upToDown',
		bpm: 100,
		message: 'Você está ficando fera! Ganhou o sexto troféu!',
		quantityOfStrings: 6,
		points: 120,
	},
	{
		number: 141,
		level: 'Avançado I',
		firstFinger: 0,
		stringNumber: 'downToUp',
		bpm: 102,
		message: '',
		quantityOfStrings: 6,
		points: 70,
	},
	{
		number: 142,
		level: 'Avançado I',
		firstFinger: 1,
		stringNumber: 'upToDown',
		bpm: 104,
		message: '',
		quantityOfStrings: 6,
		points: 70,
	},
	{
		number: 143,
		level: 'Avançado I',
		firstFinger: 2,
		stringNumber: 'downToUp',
		bpm: 106,
		message: '',
		quantityOfStrings: 6,
		points: 70,
	},
	{
		number: 144,
		level: 'Avançado I',
		firstFinger: 3,
		stringNumber: 'upToDown',
		bpm: 108,
		message: '',
		quantityOfStrings: 6,
		points: 70,
	},
	{
		number: 145,
		level: 'Avançado I',
		firstFinger: 4,
		stringNumber: 'downToUp',
		bpm: 110,
		message: '',
		quantityOfStrings: 6,
		points: 70,
	},
	{
		number: 146,
		level: 'Avançado I',
		firstFinger: 0,
		stringNumber: 'upToDown',
		bpm: 112,
		message: '',
		quantityOfStrings: 6,
		points: 70,
	},
	{
		number: 147,
		level: 'Avançado I',
		firstFinger: 1,
		stringNumber: 'downToUp',
		bpm: 114,
		message: '',
		quantityOfStrings: 6,
		points: 70,
	},
	{
		number: 148,
		level: 'Avançado I',
		firstFinger: 2,
		stringNumber: 'upToDown',
		bpm: 116,
		message: '',
		quantityOfStrings: 6,
		points: 70,
	},
	{
		number: 149,
		level: 'Avançado I',
		firstFinger: 3,
		stringNumber: 'downToUp',
		bpm: 118,
		message: '',
		quantityOfStrings: 6,
		points: 70,
	},
	{
		number: 150,
		level: 'Avançado I',
		firstFinger: 4,
		stringNumber: 'upToDown',
		bpm: 120,
		message: '',
		quantityOfStrings: 6,
		points: 70,
	},
	{
		number: 151,
		level: 'Avançado I',
		firstFinger: 0,
		stringNumber: 'downToUp',
		bpm: 122,
		message: '',
		quantityOfStrings: 6,
		points: 70,
	},
	{
		number: 152,
		level: 'Avançado I',
		firstFinger: 1,
		stringNumber: 'upToDown',
		bpm: 124,
		message: '',
		quantityOfStrings: 6,
		points: 70,
	},
	{
		number: 153,
		level: 'Avançado I',
		firstFinger: 2,
		stringNumber: 'downToUp',
		bpm: 126,
		message: '',
		quantityOfStrings: 6,
		points: 70,
	},
	{
		number: 154,
		level: 'Avançado I',
		firstFinger: 3,
		stringNumber: 'upToDown',
		bpm: 128,
		message: '',
		quantityOfStrings: 6,
		points: 70,
	},
	{
		number: 155,
		level: 'Avançado I',
		firstFinger: 4,
		stringNumber: 'downToUp',
		bpm: 130,
		message: '',
		quantityOfStrings: 6,
		points: 70,
	},
	{
		number: 156,
		level: 'Avançado I',
		firstFinger: 0,
		stringNumber: 'upToDown',
		bpm: 132,
		message: '',
		quantityOfStrings: 6,
		points: 70,
	},
	{
		number: 157,
		level: 'Avançado I',
		firstFinger: 1,
		stringNumber: 'downToUp',
		bpm: 134,
		message: '',
		quantityOfStrings: 6,
		points: 70,
	},
	{
		number: 158,
		level: 'Avançado I',
		firstFinger: 2,
		stringNumber: 'upToDown',
		bpm: 136,
		message: '',
		quantityOfStrings: 6,
		points: 70,
	},
	{
		number: 159,
		level: 'Avançado I',
		firstFinger: 3,
		stringNumber: 'downToUp',
		bpm: 138,
		message: '',
		quantityOfStrings: 6,
		points: 70,
	},
	{
		number: 160,
		level: 'Avançado I',
		firstFinger: 4,
		stringNumber: 'upToDown',
		bpm: 140,
		message: '',
		quantityOfStrings: 6,
		points: 70,
	},
	{
		number: 161,
		level: 'Avançado I',
		firstFinger: 0,
		stringNumber: 'downToUp',
		bpm: 142,
		message: '',
		quantityOfStrings: 6,
		points: 70,
	},
	{
		number: 162,
		level: 'Avançado I',
		firstFinger: 1,
		stringNumber: 'upToDown',
		bpm: 144,
		message: '',
		quantityOfStrings: 6,
		points: 70,
	},
	{
		number: 163,
		level: 'Avançado I',
		firstFinger: 2,
		stringNumber: 'downToUp',
		bpm: 146,
		message: '',
		quantityOfStrings: 6,
		points: 70,
	},
	{
		number: 164,
		level: 'Avançado I',
		firstFinger: 3,
		stringNumber: 'upToDown',
		bpm: 148,
		message: '',
		quantityOfStrings: 6,
		points: 70,
	},
	{
		number: 165,
		level: 'Avançado I',
		firstFinger: 4,
		stringNumber: 'downToUp',
		bpm: 150,
		message: 'Ganhou o sétimo troféu!',
		quantityOfStrings: 6,
		points: 140,
	},
	{
		number: 166,
		level: 'Avançado II',
		firstFinger: 0,
		stringNumber: 'upToDown',
		bpm: 152,
		message: '',
		quantityOfStrings: 6,
		points: 80,
	},
	{
		number: 167,
		level: 'Avançado II',
		firstFinger: 1,
		stringNumber: 'downToUp',
		bpm: 154,
		message: '',
		quantityOfStrings: 6,
		points: 80,
	},
	{
		number: 168,
		level: 'Avançado II',
		firstFinger: 2,
		stringNumber: 'upToDown',
		bpm: 156,
		message: '',
		quantityOfStrings: 6,
		points: 80,
	},
	{
		number: 169,
		level: 'Avançado II',
		firstFinger: 3,
		stringNumber: 'downToUp',
		bpm: 158,
		message: '',
		quantityOfStrings: 6,
		points: 80,
	},
	{
		number: 170,
		level: 'Avançado II',
		firstFinger: 4,
		stringNumber: 'upToDown',
		bpm: 160,
		message: '',
		quantityOfStrings: 6,
		points: 80,
	},
	{
		number: 171,
		level: 'Avançado II',
		firstFinger: 0,
		stringNumber: 'downToUp',
		bpm: 162,
		message: '',
		quantityOfStrings: 6,
		points: 80,
	},
	{
		number: 172,
		level: 'Avançado II',
		firstFinger: 1,
		stringNumber: 'upToDown',
		bpm: 164,
		message: '',
		quantityOfStrings: 6,
		points: 80,
	},
	{
		number: 173,
		level: 'Avançado II',
		firstFinger: 2,
		stringNumber: 'downToUp',
		bpm: 166,
		message: '',
		quantityOfStrings: 6,
		points: 80,
	},
	{
		number: 174,
		level: 'Avançado II',
		firstFinger: 3,
		stringNumber: 'upToDown',
		bpm: 168,
		message: '',
		quantityOfStrings: 6,
		points: 80,
	},
	{
		number: 175,
		level: 'Avançado II',
		firstFinger: 4,
		stringNumber: 'downToUp',
		bpm: 170,
		message: '',
		quantityOfStrings: 6,
		points: 80,
	},
	{
		number: 176,
		level: 'Avançado II',
		firstFinger: 0,
		stringNumber: 'upToDown',
		bpm: 172,
		message: '',
		quantityOfStrings: 6,
		points: 80,
	},
	{
		number: 177,
		level: 'Avançado II',
		firstFinger: 1,
		stringNumber: 'downToUp',
		bpm: 174,
		message: '',
		quantityOfStrings: 6,
		points: 80,
	},
	{
		number: 178,
		level: 'Avançado II',
		firstFinger: 2,
		stringNumber: 'upToDown',
		bpm: 176,
		message: '',
		quantityOfStrings: 6,
		points: 80,
	},
	{
		number: 179,
		level: 'Avançado II',
		firstFinger: 3,
		stringNumber: 'downToUp',
		bpm: 178,
		message: '',
		quantityOfStrings: 6,
		points: 80,
	},
	{
		number: 180,
		level: 'Avançado II',
		firstFinger: 4,
		stringNumber: 'upToDown',
		bpm: 180,
		message: '',
		quantityOfStrings: 6,
		points: 80,
	},
	{
		number: 181,
		level: 'Avançado II',
		firstFinger: 0,
		stringNumber: 'downToUp',
		bpm: 182,
		message: '',
		quantityOfStrings: 6,
		points: 80,
	},
	{
		number: 182,
		level: 'Avançado II',
		firstFinger: 1,
		stringNumber: 'upToDown',
		bpm: 184,
		message: '',
		quantityOfStrings: 6,
		points: 80,
	},
	{
		number: 183,
		level: 'Avançado II',
		firstFinger: 2,
		stringNumber: 'downToUp',
		bpm: 186,
		message: '',
		quantityOfStrings: 6,
		points: 80,
	},
	{
		number: 184,
		level: 'Avançado II',
		firstFinger: 3,
		stringNumber: 'upToDown',
		bpm: 188,
		message: '',
		quantityOfStrings: 6,
		points: 80,
	},
	{
		number: 185,
		level: 'Avançado II',
		firstFinger: 4,
		stringNumber: 'downToUp',
		bpm: 190,
		message: '',
		quantityOfStrings: 6,
		points: 80,
	},
	{
		number: 186,
		level: 'Avançado II',
		firstFinger: 0,
		stringNumber: 'upToDown',
		bpm: 192,
		message: '',
		quantityOfStrings: 6,
		points: 80,
	},
	{
		number: 187,
		level: 'Avançado II',
		firstFinger: 1,
		stringNumber: 'downToUp',
		bpm: 194,
		message: '',
		quantityOfStrings: 6,
		points: 80,
	},
	{
		number: 188,
		level: 'Avançado II',
		firstFinger: 2,
		stringNumber: 'upToDown',
		bpm: 196,
		message: '',
		quantityOfStrings: 6,
		points: 80,
	},
	{
		number: 189,
		level: 'Avançado II',
		firstFinger: 3,
		stringNumber: 'downToUp',
		bpm: 198,
		message: '',
		quantityOfStrings: 6,
		points: 80,
	},
	{
		number: 190,
		level: 'Avançado II',
		firstFinger: 4,
		stringNumber: 'upToDown',
		bpm: 200,
		message:
			'Você zerou o jogo! Parabéns! Ganhou o mega troféu e seu nome no hall de usuário mestre!',
		quantityOfStrings: 6,
		points: 160,
	},
] as Lesson[]

function getLessons() {
	return lessons
}

export const useSixStrings = () => {
	return { getLessons }
}
